using System.Globalization;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Seminco.Application.Operaciones;
using Seminco.Application.OperacionesV2;
using Seminco.Domain.OperacionesV2;
using Seminco.Infrastructure.Persistence;

namespace Seminco.Infrastructure.OperacionesV2;

public sealed class OperacionScissorV2Service(SemincoDbContext db) : IOperacionScissorV2Service
{
    private const string TipoOperacion = "scissor";
    private const string Proceso = "SCISSOR";
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };
    private IQueryable<OperacionScissor> ReadQuery() => db.OperacionesScissorV2.AsNoTracking().AsSplitQuery().Include(x => x.CondicionEquipo).Include(x => x.Horometros).Include(x => x.ChecklistRespuestas).Include(x => x.ControlLlantas).Include(x => x.Registros.OrderBy(r => r.Id)).ThenInclude(x => x.Detalle);
    public async Task<List<OperacionDto>> GetAllAsync(string? estado, string? envio, CancellationToken ct) { var q = ReadQuery(); if (estado is not null) q = q.Where(x => x.Estado == estado); if (envio is not null) q = q.Where(x => x.Envio == int.Parse(envio)); return (await q.OrderByDescending(x => x.Id).ToListAsync(ct)).Select(MapToDto).ToList(); }
    public async Task<List<OperacionDto>> GetByAprobacionAsync(string? estado, string? envio, CancellationToken ct) { var q = ReadQuery().Where(x => x.Aprobacion == 0 || x.Aprobacion == 1); if (estado is not null) q = q.Where(x => x.Estado == estado); if (envio is not null) q = q.Where(x => x.Envio == int.Parse(envio)); return (await q.OrderByDescending(x => x.Id).ToListAsync(ct)).Select(MapToDto).ToList(); }
    public async Task<OperacionDto?> GetByIdAsync(int id, CancellationToken ct) => await ReadQuery().FirstOrDefaultAsync(x => x.Id == id, ct) is { } e ? MapToDto(e) : null;
    public async Task<List<OperacionDto>> GetByJefeAsync(string jefeGuardia, int limit, int offset, CancellationToken ct) => (await ReadQuery().Where(x => x.JefeGuardia == jefeGuardia).OrderByDescending(x => x.Id).Skip(offset).Take(limit).ToListAsync(ct)).Select(MapToDto).ToList();
    public async Task<OperacionScissorV2ResponseDto> CreateAsync(JsonElement body, CancellationToken ct) { var e = new OperacionScissor { CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow }; await ApplyRequestAsync(e, Deserialize(body), body.GetRawText(), ct, false); db.OperacionesScissorV2.Add(e); await db.SaveChangesAsync(ct); return new(e.Id, "Operación scissor V2 creada correctamente"); }
    public async Task<OperacionScissorV2ResponseDto?> UpdateAsync(int id, JsonElement body, CancellationToken ct) { var e = await db.OperacionesScissorV2.Include(x => x.CondicionEquipo).Include(x => x.Horometros).Include(x => x.ChecklistRespuestas).Include(x => x.ControlLlantas).Include(x => x.Registros).ThenInclude(x => x.Detalle).FirstOrDefaultAsync(x => x.Id == id, ct); if (e is null) return null; await ApplyRequestAsync(e, Deserialize(body), body.GetRawText(), ct, true); await db.SaveChangesAsync(ct); return new(e.Id, "Operación scissor V2 actualizada correctamente"); }
    private async Task ApplyRequestAsync(OperacionScissor e, OperacionScissorUpsertRequest r, string raw, CancellationToken ct, bool update)
    {
        e.Fecha = ParseFecha(r.Fecha); e.Turno = r.Turno; e.Operador = r.Operador; e.JefeGuardia = r.JefeGuardia; e.EquipoNombre = r.Equipo; e.NEquipo = r.NEquipo; e.Seccion = r.Seccion; e.SeccionId = await ResolveSeccionIdAsync(r.Seccion, ct); e.ModeloEquipo = r.ModeloEquipo; e.Estado = string.IsNullOrWhiteSpace(r.Estado) ? "activo" : r.Estado; e.Envio = r.Envio ?? 0; e.Revisado = r.Revisado ?? 0; e.Aprobacion = r.Aprobacion ?? 0; e.ObservacionesJefe = r.ObservacionesJefe?.GetRawText(); e.ObservacionesJefe2 = r.ObservacionesJefe2?.GetRawText(); e.ObservacionesJefe3 = r.ObservacionesJefe3?.GetRawText(); e.PayloadOriginal = raw; e.PayloadVersion = "v2-json-input"; e.UpdatedAt = DateTime.UtcNow;
        if (update) { if (e.CondicionEquipo is not null) db.Remove(e.CondicionEquipo); if (e.Horometros.Count > 0) db.RemoveRange(e.Horometros); if (e.ChecklistRespuestas.Count > 0) db.RemoveRange(e.ChecklistRespuestas); if (e.ControlLlantas.Count > 0) db.RemoveRange(e.ControlLlantas); if (e.Registros.Count > 0) db.RemoveRange(e.Registros); e.CondicionEquipo = null; e.Horometros.Clear(); e.ChecklistRespuestas.Clear(); e.ControlLlantas.Clear(); e.Registros.Clear(); }
        e.Horometros = BuildHorometros(r.Horometros); e.CondicionEquipo = BuildCondicionEquipo(r.CondicionesEquipo); e.ChecklistRespuestas = await BuildChecklistAsync(r.CheckList, ct); e.ControlLlantas = BuildControlLlantas(r.ControlLlantas); e.Registros = await BuildRegistrosAsync(r.Registros, ct);
    }
    private static OperacionScissorUpsertRequest Deserialize(JsonElement body) => JsonSerializer.Deserialize<OperacionScissorUpsertRequest>(body.GetRawText(), JsonOptions) ?? throw new InvalidOperationException("No se pudo deserializar la operación scissor V2");
    private static DateTime ParseFecha(string? value) { if (string.IsNullOrWhiteSpace(value)) throw new InvalidOperationException("El campo fecha es obligatorio"); if (DateTime.TryParseExact(value, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var exact)) return DateTime.SpecifyKind(exact, DateTimeKind.Utc); if (DateTime.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var parsed)) return parsed.ToUniversalTime(); throw new InvalidOperationException($"Fecha inválida: {value}"); }
    private static TimeOnly? ParseHoraNullable(string? value) => string.IsNullOrWhiteSpace(value) ? null : TimeOnly.TryParse(value, CultureInfo.InvariantCulture, out var t) ? t : null;
    private static TimeOnly ParseHoraRequired(string value, string fieldName) => TimeOnly.TryParse(value, CultureInfo.InvariantCulture, out var t) ? t : throw new InvalidOperationException($"Hora inválida en {fieldName}: {value}");
    private static JsonElement? ParseJson(string? value) { if (string.IsNullOrWhiteSpace(value)) return null; try { return JsonSerializer.Deserialize<JsonElement>(value); } catch { return JsonDocument.Parse($"\"{value}\"").RootElement.Clone(); } }
    private static JsonElement? ToJsonElement<T>(T value) => value is null ? null : JsonSerializer.SerializeToElement(value, JsonOptions);
    private static List<OperacionScissorHorometro> BuildHorometros(JsonElement? horometros) { var result = new List<OperacionScissorHorometro>(); if (horometros is null || horometros.Value.ValueKind != JsonValueKind.Object) return result; foreach (var p in horometros.Value.EnumerateObject()) { if (p.Value.ValueKind != JsonValueKind.Object) continue; var d = JsonSerializer.Deserialize<HorometroDetalleRequest>(p.Value.GetRawText(), JsonOptions); if (d is null) continue; result.Add(new() { Tipo = p.Name.ToLowerInvariant(), Inicio = d.Inicio, Final = d.Final, Op = d.Op, Inop = d.Inop }); } return result; }
    private static OperacionScissorCondicionEquipo? BuildCondicionEquipo(CondicionEquipoRequest? r) => r is null ? null : new() { Op = r.Op, NoOp = r.NoOp, Lugar = r.Lugar, Descripcion = r.Descripcion, AceiteMotor = r.AceiteMotor, AceiteHidraulico = r.AceiteHidraulico, AceiteTransmision = r.AceiteTransmision, Combustible = r.Combustible, HoraLlenado = ParseHoraNullable(r.HoraLlenado) };
    private static List<OperacionScissorControlLlanta> BuildControlLlantas(ControlLlantasRequest? r) => r is null ? [] : [new() { Posicion = 1, Estado = r.Numero1 ?? false }, new() { Posicion = 2, Estado = r.Numero2 ?? false }, new() { Posicion = 3, Estado = r.Numero3 ?? false }, new() { Posicion = 4, Estado = r.Numero4 ?? false }];
    private async Task<List<OperacionScissorChecklistRespuesta>> BuildChecklistAsync(List<ChecklistRespuestaRequest>? r, CancellationToken ct) { if (r is null || r.Count == 0) return []; var catalog = await db.CheckListItems.AsNoTracking().Where(x => x.Proceso == Proceso).ToListAsync(ct); return r.Select(item => { var m = catalog.FirstOrDefault(c => string.Equals(c.Categoria?.Trim(), item.Categoria.Trim(), StringComparison.OrdinalIgnoreCase) && string.Equals(c.Nombre?.Trim(), item.Descripcion.Trim(), StringComparison.OrdinalIgnoreCase)); return new OperacionScissorChecklistRespuesta { ChecklistItemId = m?.Id, CategoriaSnapshot = item.Categoria, DescripcionSnapshot = item.Descripcion, Decision = item.Decision, Observacion = item.Observacion }; }).ToList(); }
    private async Task<List<OperacionScissorRegistro>> BuildRegistrosAsync(List<OperacionScissorRegistroRequest>? r, CancellationToken ct) { if (r is null || r.Count == 0) return []; var estados = await db.Estados.AsNoTracking().Where(x => x.Proceso == Proceso).ToListAsync(ct); var now = DateTime.UtcNow; return r.Select(item => { var estado = estados.FirstOrDefault(x => string.Equals(x.Codigo, item.Codigo, StringComparison.OrdinalIgnoreCase)); var op = item.Operacion; var operativo = string.Equals(item.Estado?.Trim(), "OPERATIVO", StringComparison.OrdinalIgnoreCase); return new OperacionScissorRegistro { ExternalId = item.Id, Numero = item.Numero, EstadoPrincipal = item.Estado ?? string.Empty, CodigoEstado = item.Codigo ?? string.Empty, EstadoCatalogoId = estado?.Id, HoraInicio = ParseHoraRequired(item.HoraInicio, nameof(item.HoraInicio)), HoraFinal = ParseHoraRequired(item.HoraFinal, nameof(item.HoraFinal)), PayloadOperacion = JsonSerializer.Serialize(op, JsonOptions), CreatedAt = now, UpdatedAt = now, Detalle = operativo && op is not null ? new OperacionScissorRegistroDetalle { OrigenNivel = op.OrigenNivel, OrigenTipoLabor = op.OrigenTipoLabor, OrigenLabor = op.OrigenLabor, OrigenAla = op.OrigenAla, DestinoNivel = op.DestinoNivel, DestinoTipoLabor = op.DestinoTipoLabor, DestinoLabor = op.DestinoLabor, DestinoAla = op.DestinoAla, Observaciones = op.Observaciones } : null }; }).ToList(); }
    private static OperacionDto MapToDto(OperacionScissor e) { var h = e.Horometros.Count == 0 ? null : ToJsonElement(e.Horometros.ToDictionary(x => x.Tipo, x => new HorometroDetalleRequest(x.Inicio, x.Final, x.Op, x.Inop))); var c = e.CondicionEquipo is null ? null : ToJsonElement(new CondicionEquipoRequest(e.CondicionEquipo.Op, e.CondicionEquipo.NoOp, e.CondicionEquipo.Lugar, e.CondicionEquipo.Descripcion, e.CondicionEquipo.AceiteMotor, e.CondicionEquipo.AceiteHidraulico, e.CondicionEquipo.AceiteTransmision, e.CondicionEquipo.Combustible, e.CondicionEquipo.HoraLlenado?.ToString("HH:mm:ss", CultureInfo.InvariantCulture))); var cl = e.ChecklistRespuestas.Count == 0 ? null : ToJsonElement(e.ChecklistRespuestas.OrderBy(x => x.Id).Select(x => new ChecklistRespuestaRequest(x.DescripcionSnapshot, x.Decision, x.Observacion, x.CategoriaSnapshot)).ToList()); var ctl = e.ControlLlantas.Count == 0 ? null : ToJsonElement(new ControlLlantasRequest(e.ControlLlantas.FirstOrDefault(x => x.Posicion == 1)?.Estado, e.ControlLlantas.FirstOrDefault(x => x.Posicion == 2)?.Estado, e.ControlLlantas.FirstOrDefault(x => x.Posicion == 3)?.Estado, e.ControlLlantas.FirstOrDefault(x => x.Posicion == 4)?.Estado)); var r = e.Registros.Count == 0 ? null : ToJsonElement(e.Registros.OrderBy(x => x.Id).Select(x => new OperacionScissorRegistroRequest(x.ExternalId, x.Numero, x.EstadoPrincipal, x.CodigoEstado, x.HoraInicio.ToString("HH:mm:ss", CultureInfo.InvariantCulture), x.HoraFinal.ToString("HH:mm:ss", CultureInfo.InvariantCulture), x.Detalle is null ? null : new OperacionScissorRegistroDetalleRequest(x.Detalle.OrigenNivel, x.Detalle.OrigenTipoLabor, x.Detalle.OrigenLabor, x.Detalle.OrigenAla, x.Detalle.DestinoNivel, x.Detalle.DestinoTipoLabor, x.Detalle.DestinoLabor, x.Detalle.DestinoAla, x.Detalle.Observaciones))).ToList()); return new OperacionDto(e.Id, TipoOperacion, e.Fecha.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), e.Turno, e.Seccion, e.Operador, e.JefeGuardia, e.EquipoNombre, e.NEquipo, e.ModeloEquipo, null, null, null, null, r, h, c, cl, ctl, e.Estado, e.Envio, e.Revisado, e.Aprobacion, ParseJson(e.ObservacionesJefe), ParseJson(e.ObservacionesJefe2), ParseJson(e.ObservacionesJefe3)); }
    private async Task<int?> ResolveSeccionIdAsync(string? seccion, CancellationToken ct) { if (string.IsNullOrWhiteSpace(seccion)) return null; var parts = seccion.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries); var proceso = parts.Length == 2 ? parts[0].Trim().ToUpperInvariant() : Proceso; var nombre = parts.Length switch { 1 => parts[0].Trim().ToUpperInvariant(), 2 => parts[1].Trim().ToUpperInvariant(), _ => string.Empty }; if (string.IsNullOrWhiteSpace(nombre)) return null; return await db.Secciones.AsNoTracking().Where(x => x.Proceso != null && x.Nombre != null && x.Proceso.ToUpper() == proceso && x.Nombre.ToUpper() == nombre).Select(x => (int?)x.Id).FirstOrDefaultAsync(ct); }
}
