INSERT INTO estados (id, estado_principal, codigo, tipo_estado, categoria, proceso)
VALUES
  (1, 'OPERATIVO', '101', 'Perforación en mineral', 'Operativo', 'PERFORACIÓN TALADROS LARGOS'),
  (2, 'OPERATIVO', '102', 'Perforación de repaso en mineral', 'Operativo', 'PERFORACIÓN TALADROS LARGOS'),
  (3, 'OPERATIVO', '111', 'Perforación en desmonte', 'Operativo', 'PERFORACIÓN TALADROS LARGOS'),
  (4, 'OPERATIVO', '112', 'Perforación de repaso en desmonte', 'Operativo', 'PERFORACIÓN TALADROS LARGOS'),
  (5, 'OPERATIVO', '120', 'Perforación para sostenimiento', 'Operativo', 'PERFORACIÓN TALADROS LARGOS'),
  (6, 'DEMORA', '201', 'Falta de Operador', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (7, 'DEMORA', '202', 'MpL - mantenimiento preventivo de labor', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (8, 'DEMORA', '203', 'Ingreso - Salida', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (9, 'DEMORA', '204', 'Charla', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (10, 'DEMORA', '205', 'Traslado al equipo', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (11, 'DEMORA', '206', 'Inspección de equipo', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (12, 'DEMORA', '207', 'Refrigerio', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (13, 'DEMORA', '208', 'Traslado de equipo', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (14, 'DEMORA', '209', 'Falta de labor', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (15, 'DEMORA', '210', 'Falta de servicios (energía - agua - aire)', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (16, 'DEMORA', '211', 'Instalación de equipo', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (17, 'DEMORA', '212', 'Apoyo en servicios mineros', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (18, 'DEMORA', '213', 'Falta de aceros', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (19, 'DEMORA', '214', 'Falta de ventilación', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (20, 'DEMORA', '215', 'Trabajos varios', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (21, 'DEMORA', '216', 'Accidente de equipo', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (22, 'DEMORA', '217', 'Recuperación de aceros', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (23, 'MANTENIMIENTO', '301', 'Mp inicial/final', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (24, 'MANTENIMIENTO', '302', 'Mantenimiento programado', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (25, 'MANTENIMIENTO', '303', 'Mantenimiento correctivo', 'Demora', 'PERFORACIÓN TALADROS LARGOS'),
  (26, 'RESERVA', '401', 'Reserva', 'Reserva', 'PERFORACIÓN TALADROS LARGOS'),
  (27, 'FUERA DE PLAN', '501', 'Fuera De Plan', 'Fuera De Plan', 'PERFORACIÓN TALADROS LARGOS'),
  (28, 'OPERATIVO', '101', 'Perforación en mineral', 'Operativo', 'PERFORACIÓN HORIZONTAL'),
  (29, 'OPERATIVO', '102', 'Perforación de repaso en mineral', 'Operativo', 'PERFORACIÓN HORIZONTAL'),
  (30, 'OPERATIVO', '111', 'Perforación en desmonte', 'Operativo', 'PERFORACIÓN HORIZONTAL'),
  (31, 'OPERATIVO', '112', 'Perforación de repaso en desmonte', 'Operativo', 'PERFORACIÓN HORIZONTAL'),
  (32, 'OPERATIVO', '120', 'Perforación para sostenimiento', 'Operativo', 'PERFORACIÓN HORIZONTAL'),
  (33, 'DEMORA', '201', 'Falta de Operador', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (34, 'DEMORA', '202', 'MpL - mantenimiento preventivo de labor', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (35, 'DEMORA', '203', 'Ingreso - Salida', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (36, 'DEMORA', '204', 'Charla', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (37, 'DEMORA', '205', 'Traslado al equipo', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (38, 'DEMORA', '206', 'Inspección de equipo', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (39, 'DEMORA', '207', 'Refrigerio', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (40, 'DEMORA', '208', 'Traslado de equipo', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (41, 'DEMORA', '209', 'Falta de labor', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (42, 'DEMORA', '210', 'Falta de servicios (energía - agua - aire)', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (43, 'DEMORA', '211', 'Instalación de equipo', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (44, 'DEMORA', '212', 'Apoyo en servicios mineros', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (45, 'DEMORA', '213', 'Falta de aceros', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (46, 'DEMORA', '214', 'Falta de ventilación', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (47, 'DEMORA', '215', 'Trabajos varios', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (48, 'DEMORA', '216', 'Accidente de equipo', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (49, 'DEMORA', '217', 'Recuperación de aceros', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (50, 'MANTENIMIENTO', '301', 'Mp inicial/final', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (51, 'MANTENIMIENTO', '302', 'Mantenimiento programado', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (52, 'MANTENIMIENTO', '303', 'Mantenimiento correctivo', 'Demora', 'PERFORACIÓN HORIZONTAL'),
  (53, 'RESERVA', '401', 'Reserva', 'Reserva', 'PERFORACIÓN HORIZONTAL'),
  (54, 'FUERA DE PLAN', '501', 'Fuera De Plan', 'Fuera De Plan', 'PERFORACIÓN HORIZONTAL'),
  (55, 'OPERATIVO', '101', 'Limpieza de mineral', 'Operativo', 'SCOOPTRAM'),
  (56, 'OPERATIVO', '102', 'Limpieza de mineral acumulado', 'Operativo', 'SCOOPTRAM'),
  (57, 'OPERATIVO', '103', 'Carguio de mineral', 'Operativo', 'SCOOPTRAM'),
  (58, 'OPERATIVO', '111', 'Limpieza de desmonte', 'Operativo', 'SCOOPTRAM'),
  (59, 'OPERATIVO', '112', 'Limpieza desmonte acumulado', 'Operativo', 'SCOOPTRAM'),
  (60, 'OPERATIVO', '113', 'Carguio de desmonte', 'Operativo', 'SCOOPTRAM'),
  (61, 'OPERATIVO', '120', 'Relleno detrítico', 'Operativo', 'SCOOPTRAM'),
  (62, 'DEMORA', '201', 'Falta de Operador', 'Demora', 'SCOOPTRAM'),
  (63, 'DEMORA', '202', 'MpL - mantenimiento preventivo de labor', 'Demora', 'SCOOPTRAM'),
  (64, 'DEMORA', '203', 'Ingreso - Salida', 'Demora', 'SCOOPTRAM'),
  (65, 'DEMORA', '204', 'Charla', 'Demora', 'SCOOPTRAM'),
  (66, 'DEMORA', '205', 'Traslado al equipo', 'Demora', 'SCOOPTRAM'),
  (67, 'DEMORA', '206', 'Inspección de equipo', 'Demora', 'SCOOPTRAM'),
  (68, 'DEMORA', '207', 'Refrigerio', 'Demora', 'SCOOPTRAM'),
  (69, 'DEMORA', '208', 'Traslado de equipo', 'Demora', 'SCOOPTRAM'),
  (70, 'DEMORA', '209', 'Falta de labor', 'Demora', 'SCOOPTRAM'),
  (71, 'DEMORA', '210', 'Falta de servicios (energía - agua - aire)', 'Demora', 'SCOOPTRAM'),
  (72, 'DEMORA', '211', 'Traslado de materiales o equipos', 'Demora', 'SCOOPTRAM'),
  (73, 'DEMORA', '212', 'Apoyo en servicios mineros', 'Demora', 'SCOOPTRAM'),
  (74, 'DEMORA', '213', 'Mantenimiento de vías', 'Demora', 'SCOOPTRAM'),
  (75, 'DEMORA', '214', 'Falta de ventilación', 'Demora', 'SCOOPTRAM'),
  (76, 'DEMORA', '215', 'Trabajos varios', 'Demora', 'SCOOPTRAM'),
  (77, 'DEMORA', '216', 'Accidente de equipo', 'Demora', 'SCOOPTRAM'),
  (78, 'MANTENIMIENTO', '301', 'Mp inicial/final', 'Demora', 'SCOOPTRAM'),
  (79, 'MANTENIMIENTO', '302', 'Mantenimiento programado', 'Demora', 'SCOOPTRAM'),
  (80, 'MANTENIMIENTO', '303', 'Mantenimiento correctivo', 'Demora', 'SCOOPTRAM'),
  (81, 'RESERVA', '401', 'Reserva', 'Reserva', 'SCOOPTRAM'),
  (82, 'FUERA DE PLAN', '501', 'Fuera De Plan', 'Fuera De Plan', 'SCOOPTRAM'),
  (83, 'OPERATIVO', '101', 'Acarreo de mineral', 'Operativo', 'DUMPER'),
  (84, 'OPERATIVO', '102', 'Acarreo de mineral acumulado', 'Operativo', 'DUMPER'),
  (86, 'OPERATIVO', '111', 'Acarreo de desmonte', 'Operativo', 'DUMPER'),
  (87, 'OPERATIVO', '112', 'Acarreo desmonte acumulado', 'Operativo', 'DUMPER'),
  (89, 'OPERATIVO', '120', 'Relleno detrítico', 'Operativo', 'DUMPER'),
  (90, 'DEMORA', '201', 'Falta de Operador', 'Demora', 'DUMPER'),
  (91, 'DEMORA', '202', 'MpL - mantenimiento preventivo de labor', 'Demora', 'DUMPER'),
  (92, 'DEMORA', '203', 'Ingreso - Salida', 'Demora', 'DUMPER'),
  (93, 'DEMORA', '204', 'Charla', 'Demora', 'DUMPER'),
  (94, 'DEMORA', '205', 'Traslado al equipo', 'Demora', 'DUMPER'),
  (95, 'DEMORA', '206', 'Inspección de equipo', 'Demora', 'DUMPER'),
  (96, 'DEMORA', '207', 'Refrigerio', 'Demora', 'DUMPER'),
  (97, 'DEMORA', '208', 'Traslado de equipo', 'Demora', 'DUMPER'),
  (98, 'DEMORA', '209', 'Falta de labor', 'Demora', 'DUMPER'),
  (99, 'DEMORA', '210', 'Falta de servicios (energía - agua - aire)', 'Demora', 'DUMPER'),
  (100, 'DEMORA', '211', 'Traslado de materiales o equipos', 'Demora', 'DUMPER'),
  (101, 'DEMORA', '212', 'Apoyo en servicios mineros', 'Demora', 'DUMPER'),
  (102, 'DEMORA', '213', 'Mantenimiento de vías', 'Demora', 'DUMPER'),
  (103, 'DEMORA', '214', 'Falta de ventilación', 'Demora', 'DUMPER'),
  (104, 'DEMORA', '215', 'Trabajos varios', 'Demora', 'DUMPER'),
  (105, 'DEMORA', '216', 'Accidente de equipo', 'Demora', 'DUMPER'),
  (106, 'MANTENIMIENTO', '301', 'Mp inicial/final', 'Demora', 'DUMPER'),
  (107, 'MANTENIMIENTO', '302', 'Mantenimiento programado', 'Demora', 'DUMPER'),
  (108, 'MANTENIMIENTO', '303', 'Mantenimiento correctivo', 'Demora', 'DUMPER'),
  (109, 'RESERVA', '401', 'Reserva', 'Reserva', 'DUMPER'),
  (110, 'FUERA DE PLAN', '501', 'Fuera De Plan', 'Fuera De Plan', 'DUMPER'),
  (111, 'OPERATIVO', '101', 'Limpieza de mineral', 'Operativo', 'EMPERNADOR'),
  (112, 'OPERATIVO', '102', 'Perforación de repaso en mineral', 'Operativo', 'EMPERNADOR'),
  (113, 'OPERATIVO', '111', 'Perforación en desmonte', 'Operativo', 'EMPERNADOR'),
  (114, 'OPERATIVO', '112', 'Perforación de repaso en desmonte', 'Operativo', 'EMPERNADOR'),
  (115, 'OPERATIVO', '120', 'Perforación para sostenimiento', 'Operativo', 'EMPERNADOR'),
  (116, 'DEMORA', '201', 'Falta de Operador', 'Demora', 'EMPERNADOR'),
  (117, 'DEMORA', '202', 'MpL - mantenimiento preventivo de labor', 'Demora', 'EMPERNADOR'),
  (118, 'DEMORA', '203', 'Ingreso - Salida', 'Demora', 'EMPERNADOR'),
  (119, 'DEMORA', '204', 'Charla', 'Demora', 'EMPERNADOR'),
  (120, 'DEMORA', '205', 'Traslado al equipo', 'Demora', 'EMPERNADOR'),
  (121, 'DEMORA', '206', 'Inspección de equipo', 'Demora', 'EMPERNADOR'),
  (122, 'DEMORA', '207', 'Refrigerio', 'Demora', 'EMPERNADOR'),
  (123, 'DEMORA', '208', 'Traslado de equipo', 'Demora', 'EMPERNADOR'),
  (124, 'DEMORA', '209', 'Falta de labor', 'Demora', 'EMPERNADOR'),
  (125, 'DEMORA', '210', 'Falta de servicios (energía - agua - aire)', 'Demora', 'EMPERNADOR'),
  (126, 'DEMORA', '211', 'Instalación de equipo', 'Demora', 'EMPERNADOR'),
  (127, 'DEMORA', '212', 'Apoyo en servicios mineros', 'Demora', 'EMPERNADOR'),
  (128, 'DEMORA', '213', 'Falta de aceros', 'Demora', 'EMPERNADOR'),
  (129, 'DEMORA', '214', 'Falta de ventilación', 'Demora', 'EMPERNADOR'),
  (130, 'DEMORA', '215', 'Trabajos varios', 'Demora', 'EMPERNADOR'),
  (131, 'DEMORA', '216', 'Accidente de equipo', 'Demora', 'EMPERNADOR'),
  (132, 'DEMORA', '217', 'Recuperación de aceros', 'Demora', 'EMPERNADOR'),
  (133, 'MANTENIMIENTO', '301', 'Mp inicial/final', 'Demora', 'EMPERNADOR'),
  (134, 'MANTENIMIENTO', '302', 'Mantenimiento programado', 'Demora', 'EMPERNADOR'),
  (135, 'MANTENIMIENTO', '303', 'Mantenimiento correctivo', 'Demora', 'EMPERNADOR'),
  (136, 'RESERVA', '401', 'Reserva', 'Reserva', 'EMPERNADOR'),
  (137, 'FUERA DE PLAN', '501', 'Fuera De Plan', 'Fuera De Plan', 'EMPERNADOR'),
  (138, 'OPERATIVO', '101', 'Traslado de materiales', 'OPERATIVO', 'SCISSOR'),
  (139, 'OPERATIVO', '102', 'Instalación - tuberías', 'OPERATIVO', 'SCISSOR'),
  (140, 'OPERATIVO', '103', 'Instalación - Mangas ventilación', 'OPERATIVO', 'SCISSOR'),
  (141, 'OPERATIVO', '104', 'Levantamiento - cable eléctrico', 'OPERATIVO', 'SCISSOR'),
  (142, 'OPERATIVO', '105', 'Apoyo carguío (voladura)', 'OPERATIVO', 'SCISSOR'),
  (143, 'OPERATIVO', '106', 'Apoyo otros servicios', 'OPERATIVO', 'SCISSOR'),
  (144, 'DEMORA', '201', 'Falta de operador', 'DEMORA', 'SCISSOR'),
  (145, 'DEMORA', '202', 'Ingreso - Salida', 'DEMORA', 'SCISSOR'),
  (146, 'DEMORA', '203', 'Charla / Capacitación', 'DEMORA', 'SCISSOR'),
  (147, 'DEMORA', '204', 'Reparto de guardia', 'DEMORA', 'SCISSOR'),
  (148, 'DEMORA', '205', 'Traslado al equipo', 'DEMORA', 'SCISSOR'),
  (149, 'DEMORA', '206', 'Inspección de equipo', 'DEMORA', 'SCISSOR'),
  (150, 'DEMORA', '207', 'Inspección de labor', 'DEMORA', 'SCISSOR'),
  (151, 'DEMORA', '208', 'Traslado de equipo', 'DEMORA', 'SCISSOR'),
  (152, 'DEMORA', '209', 'Falta de labor', 'DEMORA', 'SCISSOR'),
  (153, 'DEMORA', '210', 'Falla orden de trabajo', 'DEMORA', 'SCISSOR'),
  (154, 'DEMORA', '211', 'Falta de ventilación', 'DEMORA', 'SCISSOR'),
  (155, 'DEMORA', '212', 'Desatado de rocas', 'DEMORA', 'SCISSOR'),
  (156, 'DEMORA', '213', 'Abastecimiento equipo', 'DEMORA', 'SCISSOR'),
  (157, 'DEMORA', '214', 'Accidente de equipo', 'DEMORA', 'SCISSOR'),
  (158, 'DEMORA', '215', 'Refrigerio', 'DEMORA', 'SCISSOR'),
  (159, 'DEMORA', '216', 'Apoyo servicios mineros', 'DEMORA', 'SCISSOR'),
  (160, 'DEMORA', '217', 'Falta de energía', 'DEMORA', 'SCISSOR'),
  (161, 'MANTENIMIENTO', '301', 'Mantenimiento Preventivo', 'DEMORA', 'SCISSOR'),
  (162, 'MANTENIMIENTO', '302', 'Mantenimiento Programado', 'DEMORA', 'SCISSOR'),
  (163, 'MANTENIMIENTO', '303', 'Mantenimiento Correctivo', 'DEMORA', 'SCISSOR'),
  (164, 'MANTENIMIENTO', '304', 'Reparación Eléctrica', 'DEMORA', 'SCISSOR'),
  (165, 'MANTENIMIENTO', '305', 'Reparación Mecánica', 'DEMORA', 'SCISSOR'),
  (166, 'MANTENIMIENTO', '306', 'Reparación Llanta', 'DEMORA', 'SCISSOR'),
  (167, 'RESERVA', '401', 'RESERVA', 'RESERVA', 'SCISSOR'),
  (168, 'FUERA DE PLANTA', '501', 'FUERA DE PLANTA', 'FUERA DE PLANTA', 'SCISSOR'),
  (169, 'OPERATIVO', '101', 'Carguío de tajos', 'OPERATIVO', 'ANFOCHANGER'),
  (170, 'OPERATIVO', '102', 'Carguío de Frente', 'OPERATIVO', 'ANFOCHANGER'),
  (171, 'DEMORA', '201', 'Falta de operador', 'DEMORA', 'ANFOCHANGER'),
  (172, 'DEMORA', '202', 'Ingreso - Salida', 'DEMORA', 'ANFOCHANGER'),
  (173, 'DEMORA', '203', 'Charla - Capacitación', 'DEMORA', 'ANFOCHANGER'),
  (174, 'DEMORA', '204', 'Reparto de Guardia', 'DEMORA', 'ANFOCHANGER'),
  (175, 'DEMORA', '205', 'Traslado al equipo', 'DEMORA', 'ANFOCHANGER'),
  (176, 'DEMORA', '206', 'Inspección de labor', 'DEMORA', 'ANFOCHANGER'),
  (177, 'DEMORA', '207', 'Inspección de equipo', 'DEMORA', 'ANFOCHANGER'),
  (178, 'DEMORA', '208', 'Traslado de equipo', 'DEMORA', 'ANFOCHANGER'),
  (179, 'DEMORA', '209', 'Falta de labor', 'DEMORA', 'ANFOCHANGER'),
  (180, 'DEMORA', '210', 'Falta de servicio energía', 'DEMORA', 'ANFOCHANGER'),
  (181, 'DEMORA', '211', 'Falta orden de trabajo', 'DEMORA', 'ANFOCHANGER'),
  (182, 'DEMORA', '212', 'Falta de ventilación', 'DEMORA', 'ANFOCHANGER'),
  (183, 'DEMORA', '213', 'Desatado de rocas', 'DEMORA', 'ANFOCHANGER'),
  (184, 'DEMORA', '214', 'Accidente de equipo', 'DEMORA', 'ANFOCHANGER'),
  (185, 'DEMORA', '215', 'Refrigerio', 'DEMORA', 'ANFOCHANGER'),
  (186, 'DEMORA', '216', 'Apoyo servicios mineros', 'DEMORA', 'ANFOCHANGER'),
  (187, 'MANTENIMIENTO', '301', 'Mantenimiento Preventivo', 'DEMORA', 'ANFOCHANGER'),
  (188, 'MANTENIMIENTO', '302', 'Mantenimiento Programado', 'DEMORA', 'ANFOCHANGER'),
  (189, 'MANTENIMIENTO', '303', 'Mantenimiento Correctivo', 'DEMORA', 'ANFOCHANGER'),
  (190, 'MANTENIMIENTO', '304', 'Reparación Eléctrica', 'DEMORA', 'ANFOCHANGER'),
  (191, 'MANTENIMIENTO', '305', 'Reparación Mecánica', 'DEMORA', 'ANFOCHANGER'),
  (192, 'MANTENIMIENTO', '306', 'Reparación de Llanta', 'DEMORA', 'ANFOCHANGER'),
  (193, 'RESERVA', '401', 'RESERVA', 'RESERVA', 'ANFOCHANGER'),
  (194, 'FUERA DE PLANTA', '501', 'FUERA DE PLANTA', 'FUERA DE PLANTA', 'ANFOCHANGER'),
  (195, 'OPERATIVO', '120', 'Desate Mecanizado', 'OPERATIVO', 'ROMPEBANCOS'),
  (196, 'DEMORA', '201', 'Falta de operador', 'DEMORA', 'ROMPEBANCOS'),
  (197, 'DEMORA', '202', 'Ingreso - Salida', 'DEMORA', 'ROMPEBANCOS'),
  (198, 'DEMORA', '203', 'Charla (Capacitación)', 'DEMORA', 'ROMPEBANCOS'),
  (199, 'DEMORA', '204', 'Reparto de guantia', 'DEMORA', 'ROMPEBANCOS'),
  (200, 'DEMORA', '205', 'Traslado al equipo', 'DEMORA', 'ROMPEBANCOS'),
  (201, 'DEMORA', '206', 'Inspección de labor', 'DEMORA', 'ROMPEBANCOS'),
  (202, 'DEMORA', '207', 'Inspección de equipo', 'DEMORA', 'ROMPEBANCOS'),
  (203, 'DEMORA', '208', 'Traslado de equipo', 'DEMORA', 'ROMPEBANCOS'),
  (204, 'DEMORA', '209', 'Falta de labor', 'DEMORA', 'ROMPEBANCOS'),
  (205, 'DEMORA', '210', 'Falta de servicio', 'DEMORA', 'ROMPEBANCOS'),
  (206, 'DEMORA', '211', 'Falta de orden de trabajo', 'DEMORA', 'ROMPEBANCOS'),
  (207, 'DEMORA', '212', 'Falta de ventilación', 'DEMORA', 'ROMPEBANCOS'),
  (208, 'DEMORA', '213', 'Instalación / Desinstalación (equipo)', 'DEMORA', 'ROMPEBANCOS'),
  (209, 'DEMORA', '214', 'Desatado de rocas', 'DEMORA', 'ROMPEBANCOS'),
  (210, 'DEMORA', '215', 'Accidente de equipo', 'DEMORA', 'ROMPEBANCOS'),
  (211, 'DEMORA', '216', 'Refrigerio', 'DEMORA', 'ROMPEBANCOS'),
  (212, 'DEMORA', '217', 'Apoyo Servicios Mineros', 'DEMORA', 'ROMPEBANCOS'),
  (213, 'MANTENIMIENTO', '301', 'Mantenimiento Preventivo', 'DEMORA', 'ROMPEBANCOS'),
  (214, 'MANTENIMIENTO', '302', 'Mantenimiento Programado', 'DEMORA', 'ROMPEBANCOS'),
  (215, 'MANTENIMIENTO', '303', 'Mantenimiento Correctivo', 'DEMORA', 'ROMPEBANCOS'),
  (216, 'MANTENIMIENTO', '304', 'Reparación Eléctrica', 'DEMORA', 'ROMPEBANCOS'),
  (217, 'MANTENIMIENTO', '305', 'Reparación Mecánica', 'DEMORA', 'ROMPEBANCOS'),
  (218, 'MANTENIMIENTO', '306', 'Reparación de Llanta', 'DEMORA', 'ROMPEBANCOS'),
  (219, 'RESERVA', '401', 'RESERVA', 'RESERVA', 'ROMPEBANCOS'),
  (220, 'FUERA DE PLANTA', '501', 'FUERA DE PLANTA', 'FUERA DE PLANTA', 'ROMPEBANCOS'),
  (221, 'OPERATIVO', '120', 'Desate Mecanizado', 'OPERATIVO', 'SCALAMIN'),
  (222, 'DEMORA', '201', 'Falta de operador', 'DEMORA', 'SCALAMIN'),
  (223, 'DEMORA', '202', 'Ingreso - Salida', 'DEMORA', 'SCALAMIN'),
  (224, 'DEMORA', '203', 'Charla (Capacitación)', 'DEMORA', 'SCALAMIN'),
  (225, 'DEMORA', '204', 'Reparto de guantia', 'DEMORA', 'SCALAMIN'),
  (226, 'DEMORA', '205', 'Traslado al equipo', 'DEMORA', 'SCALAMIN'),
  (227, 'DEMORA', '206', 'Inspección de labor', 'DEMORA', 'SCALAMIN'),
  (228, 'DEMORA', '207', 'Inspección de equipo', 'DEMORA', 'SCALAMIN'),
  (229, 'DEMORA', '208', 'Traslado de equipo', 'DEMORA', 'SCALAMIN'),
  (230, 'DEMORA', '209', 'Falta de labor', 'DEMORA', 'SCALAMIN'),
  (231, 'DEMORA', '210', 'Falta de servicio', 'DEMORA', 'SCALAMIN'),
  (232, 'DEMORA', '211', 'Falta de orden de trabajo', 'DEMORA', 'SCALAMIN'),
  (233, 'DEMORA', '212', 'Falta de ventilación', 'DEMORA', 'SCALAMIN'),
  (234, 'DEMORA', '213', 'Instalación / Desinstalación (equipo)', 'DEMORA', 'SCALAMIN'),
  (235, 'DEMORA', '214', 'Desatado de rocas', 'DEMORA', 'SCALAMIN'),
  (236, 'DEMORA', '215', 'Accidente de equipo', 'DEMORA', 'SCALAMIN'),
  (237, 'DEMORA', '216', 'Refrigerio', 'DEMORA', 'SCALAMIN'),
  (238, 'DEMORA', '217', 'Apoyo Servicios Mineros', 'DEMORA', 'SCALAMIN'),
  (239, 'MANTENIMIENTO', '301', 'Mantenimiento Preventivo', 'DEMORA', 'SCALAMIN'),
  (240, 'MANTENIMIENTO', '302', 'Mantenimiento Programado', 'DEMORA', 'SCALAMIN'),
  (241, 'MANTENIMIENTO', '303', 'Mantenimiento Correctivo', 'DEMORA', 'SCALAMIN'),
  (242, 'MANTENIMIENTO', '304', 'Reparación Eléctrica', 'DEMORA', 'SCALAMIN'),
  (243, 'MANTENIMIENTO', '305', 'Reparación Mecánica', 'DEMORA', 'SCALAMIN'),
  (244, 'MANTENIMIENTO', '306', 'Reparación de Llanta', 'DEMORA', 'SCALAMIN'),
  (245, 'RESERVA', '401', 'RESERVA', 'RESERVA', 'SCALAMIN'),
  (246, 'FUERA DE PLANTA', '501', 'FUERA DE PLANTA', 'FUERA DE PLANTA', 'SCALAMIN')
ON CONFLICT (id) DO UPDATE
SET
  estado_principal = EXCLUDED.estado_principal,
  codigo = EXCLUDED.codigo,
  tipo_estado = EXCLUDED.tipo_estado,
  categoria = EXCLUDED.categoria,
  proceso = EXCLUDED.proceso;
