using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Seminco.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedChecklistItems : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                INSERT INTO checklist_items (id, proceso, categoria, nombre)
                VALUES
                (3, 'DUMPER', 'CHECK LIST (antes de arrancar el equipo)', 'Revisar nivel de aceite del motor'),
                (4, 'DUMPER', 'CHECK LIST (antes de arrancar el equipo)', 'Verificar que no haya fugas de aceite'),
                (5, 'DUMPER', 'CHECK LIST (antes de arrancar el equipo)', 'Revisar nivel del tanque de combustible'),
                (6, 'DUMPER', 'CHECK LIST (antes de arrancar el equipo)', 'Revisar e inspeccionar filtro de aire PTX'),
                (7, 'DUMPER', 'CHECK LIST (antes de arrancar el equipo)', 'Revisar nivel de aceite hidráulico'),
                (8, 'DUMPER', 'CHECK LIST (antes de arrancar el equipo)', 'Extintor de Incendio'),
                (9, 'DUMPER', 'DESPUÉS DEL ARRANQUE', '¿Existe algun sonido raro en el equipo?'),
                (10, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar funcionamiento de manometros de control'),
                (11, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar nivel de aceite de transmisión (RPM en mínimo)'),
                (12, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar y reportar fugas de aceite y petroleo'),
                (13, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Testear el freno de servicio y parqueo'),
                (14, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar el estado y funcionamiento de los faros de luz y circulina'),
                (15, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar el estado de la alarma audible (claxon) y alarma de retroceso'),
                (16, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar estado y operación del sistema de dirección'),
                (17, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar estado y operación del sistema de levante y voleo'),
                (18, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Revisar estado y operación del control de transmisión'),
                (19, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección pines y bocinas de los cilindros de dirección'),
                (20, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección pines y bocinas de los cilindros de levante'),
                (21, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección pines y bocinas del piston de volteo y cuchara'),
                (22, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección articulación del piston de volteo y cuchara'),
                (23, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección articulación de bastidor y cuchara'),
                (24, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección articulación de bastidor y chasis'),
                (25, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección articulación del central superior'),
                (26, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección articulación del central inferior'),
                (27, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección el estado de alimentacion eléctrica y conexiones'),
                (28, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección el filtro primario de petroleo (solo para equipos diesel)'),
                (29, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección correa en "v" del alaternador'),
                (30, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección de seguro adicional de pestaña en neumáticos'),
                (31, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección de conos, tacos y cadena linea a tierra'),
                (32, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección de labio de cuchara'),
                (33, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección de cinturon de seguridad'),
                (34, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspección de emisión de gases'),
                (35, 'DUMPER', 'DESPUÉS DEL ARRANQUE', 'Inspecciónde bloqueo switch master'),
                (36, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Parquear el equipo en un lugar seguro sin humedad ni caida de bancos'),
                (37, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Bajar la cuchara hasta el suelo y girar las ruedas hacia la pared si esta en rampa'),
                (38, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Poner el freno de estacionamiento, dejar el motor funcionando en vacio durante 2 a 3min. Antes de apagar'),
                (39, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Presionar el boton de parada y apagar el interruptor eléctrico'),
                (40, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Apagar las lucese interruptor la llave'),
                (41, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Poner el interruptor de caja principal en posición off'),
                (42, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Bajar el equipo y colocar cuñas en las ruedas'),
                (43, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Revisar el estado de las llantas. Reportar si es que se encuentran en mala condicion o bajas'),
                (44, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Limpiar y lavar las paredes sucias y verificar el estacionamiento correcto'),
                (45, 'DUMPER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Verificar el correcto llenado de la hoja de reporte - TPM reportando TODAS las fallas que se detectan'),
                (46, 'DUMPER', 'CHECK LIST TELEMANDO', 'Enlace trasmisor y receptor'),
                (47, 'DUMPER', 'CHECK LIST TELEMANDO', 'Encendido / Apagado transmisor'),
                (48, 'DUMPER', 'CHECK LIST TELEMANDO', 'Parada de emergencia'),
                (49, 'DUMPER', 'CHECK LIST TELEMANDO', 'Arranque (luces apagadas)'),
                (50, 'DUMPER', 'CHECK LIST TELEMANDO', 'Freno de parqueo'),
                (51, 'DUMPER', 'CHECK LIST TELEMANDO', 'Freno de servicio (botón izq.)'),
                (52, 'DUMPER', 'CHECK LIST TELEMANDO', 'Freno de servicio (botón der.)'),
                (53, 'DUMPER', 'CHECK LIST TELEMANDO', 'Aceleración'),
                (54, 'DUMPER', 'CHECK LIST TELEMANDO', 'Marcha adelante'),
                (55, 'DUMPER', 'CHECK LIST TELEMANDO', 'Prueba de equipo y para de equipo (iniciado - apagado)'),
                (56, 'DUMPER', 'CHECK LIST TELEMANDO', 'Marcha atrás'),
                (57, 'DUMPER', 'CHECK LIST TELEMANDO', 'Dirección izquierda'),
                (58, 'DUMPER', 'CHECK LIST TELEMANDO', 'Dirección derecha'),
                (59, 'DUMPER', 'CHECK LIST TELEMANDO', 'Braso arriba'),
                (60, 'DUMPER', 'CHECK LIST TELEMANDO', 'Braso abajo'),
                (61, 'DUMPER', 'CHECK LIST TELEMANDO', 'Volteo'),
                (62, 'DUMPER', 'CHECK LIST TELEMANDO', 'Cucharas'),
                (63, 'DUMPER', 'CHECK LIST TELEMANDO', 'Luces delanteras'),
                (64, 'DUMPER', 'CHECK LIST TELEMANDO', 'Luces posteriores'),
                (65, 'ANFOCHANGER', 'VERIFICACIÓN DE CONTROLES CRITICOS', 'Realizar pruebas de freno de servicio y de parqueo'),
                (66, 'ANFOCHANGER', 'VERIFICACIÓN DE CONTROLES CRITICOS', 'Revisar estado del sistema de direccion'),
                (67, 'ANFOCHANGER', 'VERIFICACIÓN DE CONTROLES CRITICOS', 'Inspección del estado del asiento del operador y cinturon de seguridad'),
                (68, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección sistema contra incendio / Extintor manual PQS'),
                (69, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección niveles de aceite, agua y batería'),
                (70, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (71, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección llantas / Llantas de repuesto (no lleva llanta de repuesto en el equipo)'),
                (72, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección fugas de aceite (mangueras hidráulicas, cilindros hidráulicos)'),
                (73, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección pines y bujes de la articulación central y brazo'),
                (74, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Sistema de bloqueo switch master'),
                (75, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Encendido / Apagado'),
                (76, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (77, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección dirección'),
                (78, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de estacionamiento'),
                (79, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección alarma de retroceso'),
                (80, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Ispección de activación de estabilizadores y cilindros hidráulicos'),
                (81, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección candena de linea a tierra'),
                (82, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección conos con cinta reflectiva, tacos y cadena linea a tierra'),
                (83, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección luces delanteras y posteriores'),
                (84, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección pertiga dielectrica'),
                (85, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección ganchos tipo "s"'),
                (86, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (87, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección canastilla para cargui de taladro (andamio de perforación no existe)'),
                (88, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección protector en espiral de mangueras hidráulicas'),
                (89, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección seguro whip-Check'),
                (90, 'ANFOCHANGER', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección monitoreo de emisión de gases'),
                (91, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección nivel de aceito hidráulico'),
                (92, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección estado de centralizador'),
                (93, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección estabilizadores    Gatas y mando final'),
                (94, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección pernos del martillo (ajustes), tirantes y soportes'),
                (95, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección de barras y shank'),
                (96, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección tensión de cadenas de avance y guías de perforación'),
                (97, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección condición de cable eléctrico'),
                (98, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección condición de cable avance'),
                (99, 'ANFOCHANGER', 'MPI (MANTENIMIENTO PREVENTIVO INICIAL)', 'Inspección condición de panel eléctrico'),
                (100, 'ANFOCHANGER', 'VERIFICAR EN FUNCIONAMIENTO', 'Revisar bomba, manual de llenado de aceite hidráulico'),
                (101, 'ANFOCHANGER', 'VERIFICAR EN FUNCIONAMIENTO', 'Fugas de aire y aceite hidráulico'),
                (102, 'ANFOCHANGER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Parquear el equipo en un lugar seguro sin humedad ni caida de bancos'),
                (103, 'ANFOCHANGER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Presionar el boton de parada y apagar el interruptor eléctrico'),
                (104, 'ANFOCHANGER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Apagar las luces y el interruptor de llave'),
                (105, 'ANFOCHANGER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Limpiar las partes sucias y verificar el estacionamiento correcto'),
                (106, 'ANFOCHANGER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Revisar y reportar el nivel de acierte que ha dejado el equipo'),
                (107, 'ANFOCHANGER', 'MANTENIMIENTO PREVENTIVO FINAL', 'Reportar en el control de equipo jumbo cualquier falla que se detecte'),
                (108, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Extintor'),
                (109, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Aceite / Agua / Batería'),
                (110, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (111, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Llantas'),
                (112, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Fugas de aceite / Combustible'),
                (113, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Pines Trabas y Seguros'),
                (114, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Sistema de bloqueo switch master'),
                (115, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Encendido / Apagado'),
                (116, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (117, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Emergencia y Parqueo'),
                (118, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de luces delanteras y posteriores'),
                (119, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Alarma de retroceso / Claxón / Circulina'),
                (120, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Alarma de activación de gatas'),
                (121, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de luces delantera y posteriores'),
                (122, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Conos, tacos y cadena linea a tierra'),
                (123, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de cilindros hidraulicos de brazo'),
                (124, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de brazo'),
                (125, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de martillo'),
                (126, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (127, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de estructura de cabina de operador'),
                (128, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección los escalones y asideros de la cabina'),
                (129, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección del sistema de lavado del equipo'),
                (130, 'SCISSOR', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección del sistema de engrase (pistola)'),
                (131, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite Hidráulico'),
                (132, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite del motor diesel'),
                (133, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite de lubricación de martillo'),
                (134, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Gatas y mando Final'),
                (135, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección pernos del martillo (ajustes), tirantes y soportes'),
                (136, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición de panel automotriz'),
                (137, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección del engrase del equipo'),
                (138, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de panel de control eléctrico'),
                (139, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección del sistema de aire acondisionado de la cabina del operador'),
                (140, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición parabrisas y plumillas'),
                (141, 'SCISSOR', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición asiento del operador'),
                (142, 'SCISSOR', 'VERIFICAR (En Funcionamiento)', 'Fugas de agua, aire, combustible y aceite hidráulico'),
                (143, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Extintor'),
                (144, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Aceite / Agua / Batería'),
                (145, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (146, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Llantas'),
                (147, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Fugas de aceite / Combustible'),
                (148, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Pines Trabas y Seguros'),
                (149, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Sistema de bloqueo switch master'),
                (150, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Encendido / Apagado'),
                (151, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (152, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Emergencia y Parqueo'),
                (153, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de luces delanteras y posteriores'),
                (154, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Alarma de retroceso / Claxón / Circulina'),
                (155, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Alarma de activación de gatas'),
                (156, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de luces delantera y posteriores'),
                (157, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Conos, tacos y cadena linea a tierra'),
                (158, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de cilindros hidraulicos de brazo'),
                (159, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de brazo'),
                (160, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de martillo'),
                (161, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (162, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de estructura de cabina de operador'),
                (163, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección los escalones y asideros de la cabina'),
                (164, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección del sistema de lavado del equipo'),
                (165, 'ROMPEBANCOS', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección del sistema de engrase (pistola)'),
                (166, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite Hidráulico'),
                (167, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite del motor diesel'),
                (168, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite de lubricación de martillo'),
                (169, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Gatas y mando Final'),
                (170, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección pernos del martillo (ajustes), tirantes y soportes'),
                (171, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición de panel automotriz'),
                (172, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección del engrase del equipo'),
                (173, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de panel de control eléctrico'),
                (174, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección del sistema de aire acondisionado de la cabina del operador'),
                (175, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición parabrisas y plumillas'),
                (176, 'ROMPEBANCOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición asiento del operador'),
                (177, 'ROMPEBANCOS', 'VERIFICAR (En Funcionamiento)', 'Lubricación de martillo'),
                (178, 'ROMPEBANCOS', 'VERIFICAR (En Funcionamiento)', 'Percución (escape del aire de percución)'),
                (179, 'ROMPEBANCOS', 'VERIFICAR (En Funcionamiento)', 'Rotación (parte delantera del martillo y retorno)'),
                (180, 'ROMPEBANCOS', 'VERIFICAR (En Funcionamiento)', 'Regulación de presiones de percusión'),
                (181, 'ROMPEBANCOS', 'VERIFICAR (En Funcionamiento)', 'Fugas de agua, aire, combustible y aceite hidráulico'),
                (182, 'ROMPEBANCOS', 'MPF (Mantenimiento preventivo final)', 'Detener el equipo en un lugar adecuado sin humedad ni caida de bancos'),
                (183, 'ROMPEBANCOS', 'MPF (Mantenimiento preventivo final)', 'Presionar el botón de parada y apagar el botón del interruptor del motor diesel'),
                (184, 'ROMPEBANCOS', 'MPF (Mantenimiento preventivo final)', 'Apagar las luces y el interruptor de llave'),
                (185, 'ROMPEBANCOS', 'MPF (Mantenimiento preventivo final)', 'Limpiar las partes sucias y verificar el estacionamiento correcto'),
                (186, 'ROMPEBANCOS', 'MPF (Mantenimiento preventivo final)', 'Revisar y reportar el nivel de acierte que ha dejado el equipo'),
                (187, 'ROMPEBANCOS', 'MPF (Mantenimiento preventivo final)', 'Reportar en el control de equipo cualquier falla que se detecte'),
                (188, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Extintor'),
                (189, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Aceite / Agua / Batería'),
                (190, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (191, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Llantas'),
                (192, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Fugas de aceite / Combustible'),
                (193, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Pines Trabas y Seguros'),
                (194, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Sistema de bloqueo switch master'),
                (195, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Encendido / Apagado'),
                (196, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (197, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Freno de Emergencia y Parqueo'),
                (198, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de luces delanteras y posteriores'),
                (199, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Alarma de retroceso / Claxón / Circulina'),
                (200, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Alarma de activación de gatas'),
                (201, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de luces delantera y posteriores'),
                (202, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Conos, tacos y cadena linea a tierra'),
                (203, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de cilindros hidraulicos de brazo'),
                (204, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de brazo'),
                (205, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de martillo'),
                (206, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (207, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección de estructura de cabina de operador'),
                (208, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección los escalones y asideros de la cabina'),
                (209, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección del sistema de lavado del equipo'),
                (210, 'SCALAMIN', 'CHECK LIST (antes de arrancar el equipo)', 'Inspección del sistema de engrase (pistola)'),
                (211, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite Hidráulico'),
                (212, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite del motor diesel'),
                (213, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite de lubricación de martillo'),
                (214, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Gatas y mando Final'),
                (215, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección pernos del martillo (ajustes), tirantes y soportes'),
                (216, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición de panel automotriz'),
                (217, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección del engrase del equipo'),
                (218, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de panel de control eléctrico'),
                (219, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección del sistema de aire acondisionado de la cabina del operador'),
                (220, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición parabrisas y plumillas'),
                (221, 'SCALAMIN', 'MPI (Mantenimiento Previo Inicial)', 'Inspección condición asiento del operador'),
                (222, 'SCALAMIN', 'VERIFICAR (En Funcionamiento)', 'Lubricación de martillo'),
                (223, 'SCALAMIN', 'VERIFICAR (En Funcionamiento)', 'Percución (escape del aire de percución)'),
                (224, 'SCALAMIN', 'VERIFICAR (En Funcionamiento)', 'Rotación (parte delantera del martillo y retorno)'),
                (225, 'SCALAMIN', 'VERIFICAR (En Funcionamiento)', 'Regulación de presiones de percusión'),
                (226, 'SCALAMIN', 'VERIFICAR (En Funcionamiento)', 'Fugas de agua, aire, combustible y aceite hidráulico'),
                (227, 'SCALAMIN', 'MPF (Mantenimiento preventivo final)', 'Detener el equipo en un lugar adecuado sin humedad ni caida de bancos'),
                (228, 'SCALAMIN', 'MPF (Mantenimiento preventivo final)', 'Presionar el botón de parada y apagar el botón del interruptor del motor diesel'),
                (229, 'SCALAMIN', 'MPF (Mantenimiento preventivo final)', 'Apagar las luces y el interruptor de llave'),
                (230, 'SCALAMIN', 'MPF (Mantenimiento preventivo final)', 'Limpiar las partes sucias y verificar el estacionamiento correcto'),
                (231, 'SCALAMIN', 'MPF (Mantenimiento preventivo final)', 'Revisar y reportar el nivel de acierte que ha dejado el equipo'),
                (232, 'SCALAMIN', 'MPF (Mantenimiento preventivo final)', 'Reportar en el control de equipo cualquier falla que se detecte'),
                (237, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Extintor'),
                (238, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Aceite / Agua / Batería'),
                (239, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (240, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Llantas / Llanta de repuesto'),
                (241, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Fugas de aceite'),
                (242, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Pines y seguros'),
                (243, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Sistema de bloque switch master'),
                (244, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Encendido'),
                (245, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (246, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Dirección'),
                (247, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Freno de estacionamiento'),
                (248, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Alarma de retroceso'),
                (249, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Alarma de activación de gatas'),
                (250, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Cadena de línea a tierra'),
                (251, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Conos, tacos y cadena línea a tierra'),
                (252, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Cartilla de parámetros de perforación'),
                (253, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Pertiga dielectrica'),
                (254, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Ganchas tipo "S"'),
                (255, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (256, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Andamio de perforación'),
                (257, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Covertores de mangueras hidraúlicas'),
                (258, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Seguro whip-check'),
                (259, 'PERFORACIÓN TALADROS LARGOS', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Monitoreo de emisión de gases'),
                (260, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite Hidráulico'),
                (261, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Estado de centralizador'),
                (262, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Gatas y mando final'),
                (263, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Pernos del Martillo (ajustes), tirantes y soportes'),
                (264, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Estado de Barras y shank'),
                (265, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Tensión de cadena de avance y guías de perforación'),
                (266, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de cable eléctrico'),
                (267, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de cable avance'),
                (268, 'PERFORACIÓN TALADROS LARGOS', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de panel de control eléctrico'),
                (269, 'PERFORACIÓN TALADROS LARGOS', 'VERIFICAR (En Funcionamiento)', 'Lubricación de martillo'),
                (270, 'PERFORACIÓN TALADROS LARGOS', 'VERIFICAR (En Funcionamiento)', 'Percusión (escape del aire de percusión)'),
                (271, 'PERFORACIÓN TALADROS LARGOS', 'VERIFICAR (En Funcionamiento)', 'Rotación (parte delantera del martillo y retorno, mangueras de rotación)'),
                (272, 'PERFORACIÓN TALADROS LARGOS', 'VERIFICAR (En Funcionamiento)', 'Avance (retorno motor de avance)'),
                (273, 'PERFORACIÓN TALADROS LARGOS', 'VERIFICAR (En Funcionamiento)', 'Fugas de agua, aire y aceite hidráulico'),
                (274, 'PERFORACIÓN TALADROS LARGOS', 'MPF (Mantenimiento Preventivo Final)', 'Detener el equipo en un lugar adecuado sin humedad ni caida de bancos'),
                (275, 'PERFORACIÓN TALADROS LARGOS', 'MPF (Mantenimiento Preventivo Final)', 'Presionar el botón de parada y apagar el botón del interruptor del motor'),
                (276, 'PERFORACIÓN TALADROS LARGOS', 'MPF (Mantenimiento Preventivo Final)', 'Apagar las luces y el interruptor de llave'),
                (277, 'PERFORACIÓN TALADROS LARGOS', 'MPF (Mantenimiento Preventivo Final)', 'Limpiar las partes sucias y verificar el estacionamiento correcto'),
                (278, 'PERFORACIÓN TALADROS LARGOS', 'MPF (Mantenimiento Preventivo Final)', 'Revisar y reportar el nivel de acierte que ha dejado el equipo'),
                (279, 'PERFORACIÓN TALADROS LARGOS', 'MPF (Mantenimiento Preventivo Final)', 'Reportar en el control de equipo Jumbo caulquier falla que se detecte'),
                (280, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Extintor'),
                (281, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Aceite / Agua / Batería'),
                (282, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (283, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Llantas / Llanta de repuesto'),
                (284, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Fugas de aceite'),
                (285, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Pines y seguros'),
                (286, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Sistema de bloque switch master'),
                (287, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Encendido'),
                (288, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (289, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Dirección'),
                (290, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Freno de estacionamiento'),
                (291, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Alarma de retroceso'),
                (292, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Alarma de activación de gatas'),
                (293, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Cadena de línea a tierra'),
                (294, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Conos, tacos y cadena línea a tierra'),
                (295, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Cartilla de parámetros de perforación'),
                (296, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Pertiga dielectrica'),
                (297, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Ganchas tipo "S"'),
                (298, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (299, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Andamio de perforación'),
                (300, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Covertores de mangueras hidraúlicas'),
                (301, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Seguro whip-check'),
                (302, 'PERFORACIÓN HORIZONTAL', 'CHECK LIST (Antes de arrancar el equipo)', 'Inspección Monitoreo de emisión de gases'),
                (303, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Nivel de Aceite Hidráulico'),
                (304, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Estado de centralizador'),
                (305, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Gatas y mando final'),
                (306, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Pernos del Martillo (ajustes), tirantes y soportes'),
                (307, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Estado de Barras y shank'),
                (308, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Tensión de cadena de avance y guías de perforación'),
                (309, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de cable eléctrico'),
                (310, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de cable avance'),
                (311, 'PERFORACIÓN HORIZONTAL', 'MPI (Mantenimiento Previo Inicial)', 'Inspección Condición de panel de control eléctrico'),
                (312, 'PERFORACIÓN HORIZONTAL', 'VERIFICAR (En Funcionamiento)', 'Lubricación de martillo'),
                (313, 'PERFORACIÓN HORIZONTAL', 'VERIFICAR (En Funcionamiento)', 'Percusión (escape del aire de percusión)'),
                (314, 'PERFORACIÓN HORIZONTAL', 'VERIFICAR (En Funcionamiento)', 'Rotación (parte delantera del martillo y retorno, mangueras de rotación)'),
                (315, 'PERFORACIÓN HORIZONTAL', 'VERIFICAR (En Funcionamiento)', 'Avance (retorno motor de avance)'),
                (316, 'PERFORACIÓN HORIZONTAL', 'VERIFICAR (En Funcionamiento)', 'Fugas de agua, aire y aceite hidráulico'),
                (317, 'PERFORACIÓN HORIZONTAL', 'MPF (Mantenimiento Preventivo Final)', 'Detener el equipo en un lugar adecuado sin humedad ni caida de bancos'),
                (318, 'PERFORACIÓN HORIZONTAL', 'MPF (Mantenimiento Preventivo Final)', 'Presionar el botón de parada y apagar el botón del interruptor del motor'),
                (319, 'PERFORACIÓN HORIZONTAL', 'MPF (Mantenimiento Preventivo Final)', 'Apagar las luces y el interruptor de llave'),
                (320, 'PERFORACIÓN HORIZONTAL', 'MPF (Mantenimiento Preventivo Final)', 'Limpiar las partes sucias y verificar el estacionamiento correcto'),
                (321, 'PERFORACIÓN HORIZONTAL', 'MPF (Mantenimiento Preventivo Final)', 'Revisar y reportar el nivel de acierte que ha dejado el equipo'),
                (322, 'PERFORACIÓN HORIZONTAL', 'MPF (Mantenimiento Preventivo Final)', 'Reportar en el control de equipo Jumbo caulquier falla que se detecte'),
                (323, 'SCOOPTRAM', 'MPI (Antes de Arrancar el Equipo)', 'Revisar nivel de aceite de motor'),
                (324, 'SCOOPTRAM', 'MPI (Antes de Arrancar el Equipo)', 'Verificar que no haya fugas de aceite'),
                (325, 'SCOOPTRAM', 'MPI (Antes de Arrancar el Equipo)', 'Revisar nivel del tanque de combustible'),
                (326, 'SCOOPTRAM', 'MPI (Antes de Arrancar el Equipo)', 'Revisar e inspeccionar filtro de aire y PTX'),
                (327, 'SCOOPTRAM', 'MPI (Antes de Arrancar el Equipo)', 'Revisar nivel de aceite hidraulico'),
                (328, 'SCOOPTRAM', 'MPI (Antes de Arrancar el Equipo)', 'Extintor de Incendio'),
                (329, 'SCOOPTRAM', 'MPI (Después del Arranque)', '¿Existe algun sonido raro en el equipo?'),
                (330, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar funcionamiento de manómetros de control'),
                (331, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar nivel de aceite de transmisión (RPM en mínimo)'),
                (332, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar y reportar fugas de aceite y petróleo'),
                (333, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Testear el freno de servicio y de parqueo'),
                (334, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar el estado y funcionamiento de los faros de luz y circulina'),
                (335, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar estado y operación del sistema de dirección'),
                (336, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar estado y operación del sistema de levante y voleo'),
                (337, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Revisar estado y operación del control de transmisión'),
                (338, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección pines y bocinas de los cilindros de dirección'),
                (339, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección pines y bocinas de los cilindros de levante'),
                (340, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección pines y bocinas del pistón de volteo de cuchara'),
                (341, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección articulación de pistón de volteo de cuchara'),
                (342, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección articulación de bastidor y cuchara'),
                (343, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección articulación de bastidor y chasis'),
                (344, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección artculación central superior'),
                (345, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección articulación central inferior'),
                (346, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección el estado de alimentación eléctrica y conexiones'),
                (347, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección el filtro primario de petróleo (solo para equipos diesel)'),
                (348, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección correa en "V" del alternador'),
                (349, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección de seguro adicional de pestaña en Neumáticos'),
                (350, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección de conos, tacos y cadena línea a tierra'),
                (351, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección de labio de cuchara'),
                (352, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Inspección de cinturón de seguridad'),
                (353, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Monitoreo de emisión de gases'),
                (354, 'SCOOPTRAM', 'MPI (Después del Arranque)', 'Sistema de bloqueo switch master'),
                (355, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Parquear el equipo en un lugar seguro sin humedad ni caida de bancos'),
                (356, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Bajar la cuchara hasta el suelo y girar las ruedas hacia la pared si está en rampa'),
                (357, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Poner el freno de estacionamiento, dejas el motor funcionando en vacío durante 2 a 3 min. Antes de apagar.'),
                (358, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Presionar el botón de parada y apagar el interruptor eléctrico'),
                (359, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Apagar las luces e interruptor de llave.'),
                (360, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Poner el interruptor de caja principal en posición off'),
                (361, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Bajar del equipo y colocar cuñas en las ruedas'),
                (362, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Revisar el estado de las llantas. Reportar si es que se encuentran en mala condición o bajas.'),
                (363, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Limpiar y lavar las partes sucias y verificar el estacionamiento correcto'),
                (364, 'SCOOPTRAM', 'MPF (Mantenimiento Preventivo Final)', 'Verificar el correcto llenado de la hojas de reporte - TPM, reportando TODAS las fallas que se detecten'),
                (365, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Enlace transmisor y receptor'),
                (366, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Encendido/Apagado transmisor'),
                (367, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Parada de emergencia'),
                (368, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Arranque (luces apagadas)'),
                (369, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Freno de parqueo'),
                (370, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Freno de servicio (botón izq.)'),
                (371, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Freno de servicio (botón der.)'),
                (372, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Aceleración'),
                (373, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Marcha adelante'),
                (374, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Prueba de equipo y para de equipo (inclinado - apagado)'),
                (375, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Marcha atrás'),
                (376, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Dirección izquierda'),
                (377, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Dirección derecha'),
                (378, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Brazo arriba'),
                (379, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Brazo abajo'),
                (380, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Volteo'),
                (381, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Cuchareo'),
                (382, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Luces delanteras'),
                (383, 'SCOOPTRAM', 'CHECKLIST (TELEMANDO)', 'Luces posteriores'),
                (384, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Extintor'),
                (385, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Aceite / Agua / Batería'),
                (386, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Protección (Partes móviles)'),
                (387, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Llantas / Llanta de repuesto'),
                (388, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Fugas de aceite'),
                (389, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Pines y seguros'),
                (390, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Sistema de bloque switch master'),
                (391, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Encendido'),
                (392, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Freno de Servicio'),
                (393, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Dirección'),
                (394, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Freno de estacionamiento'),
                (395, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Alarma de retroceso'),
                (396, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Alarma de activación de gatas'),
                (397, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Cadena de línea a tierra'),
                (398, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Conos, tacos y cadena línea a tierra'),
                (399, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Ganchas tipo "S"'),
                (400, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Kit antiderrame'),
                (401, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Andamio de perforación'),
                (402, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Covertores de mangueras hidraúlicas'),
                (403, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Seguro whip-check'),
                (404, 'EMPERNADOR', 'CHECKLIST (Antes de arrancar el equipo)', 'Inspección Monitoreo de emisión de gases'),
                (405, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Nivel de Aceite Hidráulico'),
                (406, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Estado de centralizador'),
                (407, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Gatas y mando final'),
                (408, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Pernos del Martillo (ajustes), tirantes y soportes'),
                (409, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Estado de Barras y shank'),
                (410, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Tensión de cadena de avance y guías de perforación'),
                (411, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Condición de cable eléctrico'),
                (412, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Condición de cable avance'),
                (413, 'EMPERNADOR', 'MPI (Mantenimiento Preventivo Inicial)', 'Inspección Condición de panel de control eléctrico'),
                (414, 'EMPERNADOR', 'VERIFICAR (En funcionamiento)', 'Lubricación de martillo'),
                (415, 'EMPERNADOR', 'VERIFICAR (En funcionamiento)', 'Percusión (escape del aire de percusión)'),
                (416, 'EMPERNADOR', 'VERIFICAR (En funcionamiento)', 'Rotación (parte delantera del martillo y retorno, mangueras de rotación)'),
                (417, 'EMPERNADOR', 'VERIFICAR (En funcionamiento)', 'Avance (retorno motor de avance)'),
                (418, 'EMPERNADOR', 'VERIFICAR (En funcionamiento)', 'Fugas de agua, aire y aceite hidráulico'),
                (419, 'EMPERNADOR', 'MPF (Mantenimiento Preventivo Final)', 'Detener el equipo en un lugar adecuado sin humedad ni caida de bancos'),
                (420, 'EMPERNADOR', 'MPF (Mantenimiento Preventivo Final)', 'Presionar el botón de parada y apagar el botón del interruptor del motor'),
                (421, 'EMPERNADOR', 'MPF (Mantenimiento Preventivo Final)', 'Apagar las luces y el interruptor de llave'),
                (422, 'EMPERNADOR', 'MPF (Mantenimiento Preventivo Final)', 'Limpiar las partes sucias y verificar el estacionamiento correcto'),
                (423, 'EMPERNADOR', 'MPF (Mantenimiento Preventivo Final)', 'Revisar y reportar el nivel de acierte que ha dejado el equipo'),
                (424, 'SCISSOR', 'VERIFICAR', 'Lubricación de martillo'),
                (425, 'SCISSOR', 'VERIFICAR', 'Percusión (escape del aire de percusión)'),
                (426, 'SCISSOR', 'VERIFICAR', 'Rotación (parte delantera del martillo y retorno)'),
                (427, 'SCISSOR', 'VERIFICAR', 'Regulación de presiones de percusión'),
                (428, 'ANFOCHANGER', 'ANTES', 'Inspección guardas de seguridad (Partes móviles)'),
                (429, 'ANFOCHANGER', 'VERIFICAR', 'Fugas por cilindros de gatas'),
                (430, 'ANFOCHANGER', 'VERIFICAR', 'Fuga de aceite cilindro basculación'),
                (433, 'ANFOCHANGER', 'VERIFICAR', 'Fuga de aceite por cilindro levante del brazo'),
                (434, 'EMPERNADOR', 'ANTES', 'Inspección Pertiga dieléctrica')
                ON CONFLICT (id) DO UPDATE
                SET
                  proceso = EXCLUDED.proceso,
                  categoria = EXCLUDED.categoria,
                  nombre = EXCLUDED.nombre;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM checklist_items WHERE id IN (3,4,5,6,7,8,9);");
        }
    }
}
