using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Seminco.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SyncExistingSchemaObjects : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF to_regclass('public."Operacion_tal_largo"') IS NULL AND to_regclass('public.operacion_tal_largo') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_tal_largo RENAME TO "Operacion_tal_largo"';
                    END IF;
                    IF to_regclass('public."Operacion_tal_horizontal"') IS NULL AND to_regclass('public.operacion_tal_horizontal') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_tal_horizontal RENAME TO "Operacion_tal_horizontal"';
                    END IF;
                    IF to_regclass('public."Operacion_empernador"') IS NULL AND to_regclass('public.operacion_empernador') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_empernador RENAME TO "Operacion_empernador"';
                    END IF;
                    IF to_regclass('public."Operacion_carguio"') IS NULL AND to_regclass('public.operacion_carguio') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_carguio RENAME TO "Operacion_carguio"';
                    END IF;
                    IF to_regclass('public."Operacion_rompebanco"') IS NULL AND to_regclass('public.operacion_rompebanco') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_rompebanco RENAME TO "Operacion_rompebanco"';
                    END IF;
                    IF to_regclass('public."Operacion_scissor"') IS NULL AND to_regclass('public.operacion_scissor') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_scissor RENAME TO "Operacion_scissor"';
                    END IF;
                    IF to_regclass('public."Operacion_anfochanger"') IS NULL AND to_regclass('public.operacion_anfochanger') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_anfochanger RENAME TO "Operacion_anfochanger"';
                    END IF;
                    IF to_regclass('public."Operacion_scalamin"') IS NULL AND to_regclass('public.operacion_scalamin') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_scalamin RENAME TO "Operacion_scalamin"';
                    END IF;
                    IF to_regclass('public."Operacion_dumper"') IS NULL AND to_regclass('public.operacion_dumper') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE operacion_dumper RENAME TO "Operacion_dumper"';
                    END IF;
                    IF to_regclass('public.tipo_perforaciones') IS NULL AND to_regclass('public.tipoperforacions') IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE tipoperforacions RENAME TO tipo_perforaciones';
                    END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS tipo_perforaciones (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    nombre text NOT NULL,
                    proceso text,
                    permitido_medicion integer,
                    CONSTRAINT "PK_tipo_perforaciones" PRIMARY KEY (id)
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_v2 (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha timestamp with time zone NOT NULL,
                    turno text,
                    operador text,
                    jefe_guardia text,
                    equipo_id integer,
                    equipo_nombre text,
                    n_equipo text,
                    seccion text,
                    seccion_id integer,
                    capacidad text,
                    tipo_equipo_diesel boolean,
                    tipo_equipo_electrico boolean,
                    estado text NOT NULL,
                    envio integer NOT NULL,
                    revisado integer NOT NULL,
                    aprobacion integer NOT NULL,
                    observaciones_jefe text,
                    observaciones_jefe2 text,
                    observaciones_jefe3 text,
                    payload_original jsonb,
                    payload_version text,
                    external_sync_id text,
                    device_id text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_carguio_v2" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_carguio_v2_secciones_seccion_id" FOREIGN KEY (seccion_id) REFERENCES secciones (id) ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_v2 (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha timestamp with time zone NOT NULL,
                    turno text,
                    operador text,
                    jefe_guardia text,
                    equipo_id integer,
                    equipo_nombre text,
                    n_equipo text,
                    seccion text,
                    seccion_id integer,
                    tipo_equipo_diesel boolean,
                    tipo_equipo_electrico boolean,
                    estado text NOT NULL,
                    envio integer NOT NULL,
                    revisado integer NOT NULL,
                    aprobacion integer NOT NULL,
                    observaciones_jefe text,
                    observaciones_jefe2 text,
                    observaciones_jefe3 text,
                    payload_original jsonb,
                    payload_version text,
                    external_sync_id text,
                    device_id text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_empernador_v2" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_empernador_v2_secciones_seccion_id" FOREIGN KEY (seccion_id) REFERENCES secciones (id) ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_v2 (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha timestamp with time zone NOT NULL,
                    turno text,
                    operador text,
                    jefe_guardia text,
                    equipo_id integer,
                    equipo_nombre text,
                    n_equipo text,
                    seccion text,
                    seccion_id integer,
                    modelo_equipo text,
                    estado text NOT NULL,
                    envio integer NOT NULL,
                    revisado integer NOT NULL,
                    aprobacion integer NOT NULL,
                    observaciones_jefe text,
                    observaciones_jefe2 text,
                    observaciones_jefe3 text,
                    payload_original jsonb,
                    payload_version text,
                    external_sync_id text,
                    device_id text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_scalamin_v2" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scalamin_v2_secciones_seccion_id" FOREIGN KEY (seccion_id) REFERENCES secciones (id) ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_v2 (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha timestamp with time zone NOT NULL,
                    turno text,
                    operador text,
                    jefe_guardia text,
                    equipo_id integer,
                    equipo_nombre text,
                    n_equipo text,
                    seccion text,
                    seccion_id integer,
                    modelo_equipo text,
                    estado text NOT NULL,
                    envio integer NOT NULL,
                    revisado integer NOT NULL,
                    aprobacion integer NOT NULL,
                    observaciones_jefe text,
                    observaciones_jefe2 text,
                    observaciones_jefe3 text,
                    payload_original jsonb,
                    payload_version text,
                    external_sync_id text,
                    device_id text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_scissor_v2" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scissor_v2_secciones_seccion_id" FOREIGN KEY (seccion_id) REFERENCES secciones (id) ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_v2 (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha timestamp with time zone NOT NULL,
                    turno text,
                    operador text,
                    jefe_guardia text,
                    equipo_id integer,
                    equipo_nombre text,
                    n_equipo text,
                    seccion text,
                    seccion_id integer,
                    modelo_equipo text,
                    estado text NOT NULL,
                    envio integer NOT NULL,
                    revisado integer NOT NULL,
                    aprobacion integer NOT NULL,
                    observaciones_jefe text,
                    observaciones_jefe2 text,
                    observaciones_jefe3 text,
                    payload_original jsonb,
                    payload_version text,
                    external_sync_id text,
                    device_id text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_tal_horizontal_v2" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_horizontal_v2_secciones_seccion_id" FOREIGN KEY (seccion_id) REFERENCES secciones (id) ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_v2 (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha timestamp with time zone NOT NULL,
                    turno text,
                    operador text,
                    jefe_guardia text,
                    equipo_id integer,
                    equipo_nombre text,
                    n_equipo text,
                    seccion text,
                    seccion_id integer,
                    modelo_equipo text,
                    estado text NOT NULL,
                    envio integer NOT NULL,
                    revisado integer NOT NULL,
                    aprobacion integer NOT NULL,
                    observaciones_jefe text,
                    observaciones_jefe2 text,
                    observaciones_jefe3 text,
                    payload_original jsonb,
                    payload_version text,
                    external_sync_id text,
                    device_id text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_tal_largo_v2" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_largo_v2_secciones_seccion_id" FOREIGN KEY (seccion_id) REFERENCES secciones (id) ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_checklist (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    checklist_item_id integer,
                    categoria_snapshot text NOT NULL,
                    descripcion_snapshot text NOT NULL,
                    decision integer NOT NULL,
                    observacion text,
                    CONSTRAINT "PK_operacion_carguio_checklist" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_carguio_checklist_checklist_items_checklist_item_~" FOREIGN KEY (checklist_item_id) REFERENCES checklist_items (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_operacion_carguio_checklist_operacion_carguio_v2_operacion_~" FOREIGN KEY (operacion_id) REFERENCES operacion_carguio_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_condicion_equipo (
                    operacion_id integer NOT NULL,
                    op boolean NOT NULL,
                    no_op boolean NOT NULL,
                    lugar text,
                    descripcion text,
                    aceite_motor boolean NOT NULL,
                    aceite_hidraulico boolean NOT NULL,
                    aceite_transmision boolean NOT NULL,
                    combustible text,
                    hora_llenado time without time zone,
                    CONSTRAINT "PK_operacion_carguio_condicion_equipo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_carguio_condicion_equipo_operacion_carguio_v2_ope~" FOREIGN KEY (operacion_id) REFERENCES operacion_carguio_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_control_llanta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    posicion smallint NOT NULL,
                    estado boolean NOT NULL,
                    presion numeric(10,2),
                    observacion text,
                    CONSTRAINT "PK_operacion_carguio_control_llanta" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_carguio_control_llanta_operacion_carguio_v2_opera~" FOREIGN KEY (operacion_id) REFERENCES operacion_carguio_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_horometro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    tipo text NOT NULL,
                    inicio numeric(10,2),
                    final numeric(10,2),
                    op boolean NOT NULL,
                    inop boolean NOT NULL,
                    CONSTRAINT "PK_operacion_carguio_horometro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_carguio_horometro_operacion_carguio_v2_operacion_~" FOREIGN KEY (operacion_id) REFERENCES operacion_carguio_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_programa_trabajo (
                    operacion_id integer NOT NULL,
                    n_cucharas_programado integer,
                    n_cucharas_realizado integer,
                    CONSTRAINT "PK_operacion_carguio_programa_trabajo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_carguio_programa_trabajo_operacion_carguio_v2_ope~" FOREIGN KEY (operacion_id) REFERENCES operacion_carguio_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_registro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    external_id bigint,
                    numero integer NOT NULL,
                    estado_principal text NOT NULL,
                    codigo_estado text NOT NULL,
                    estado_catalogo_id integer,
                    hora_inicio time without time zone NOT NULL,
                    hora_final time without time zone NOT NULL,
                    payload_operacion jsonb,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_carguio_registro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_carguio_registro_operacion_carguio_v2_operacion_id" FOREIGN KEY (operacion_id) REFERENCES operacion_carguio_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_checklist (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    checklist_item_id integer,
                    categoria_snapshot text NOT NULL,
                    descripcion_snapshot text NOT NULL,
                    decision integer NOT NULL,
                    observacion text,
                    CONSTRAINT "PK_operacion_empernador_checklist" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_empernador_checklist_checklist_items_checklist_it~" FOREIGN KEY (checklist_item_id) REFERENCES checklist_items (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_operacion_empernador_checklist_operacion_empernador_v2_oper~" FOREIGN KEY (operacion_id) REFERENCES operacion_empernador_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_condicion_equipo (
                    operacion_id integer NOT NULL,
                    op boolean NOT NULL,
                    no_op boolean NOT NULL,
                    lugar text,
                    descripcion text,
                    aceite_motor boolean NOT NULL,
                    aceite_hidraulico boolean NOT NULL,
                    aceite_transmision boolean NOT NULL,
                    combustible text,
                    hora_llenado time without time zone,
                    CONSTRAINT "PK_operacion_empernador_condicion_equipo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_empernador_condicion_equipo_operacion_empernador_~" FOREIGN KEY (operacion_id) REFERENCES operacion_empernador_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_control_llanta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    posicion smallint NOT NULL,
                    estado boolean NOT NULL,
                    presion numeric(10,2),
                    observacion text,
                    CONSTRAINT "PK_operacion_empernador_control_llanta" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_empernador_control_llanta_operacion_empernador_v2~" FOREIGN KEY (operacion_id) REFERENCES operacion_empernador_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_horometro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    tipo text NOT NULL,
                    inicio numeric(10,2),
                    final numeric(10,2),
                    op boolean NOT NULL,
                    inop boolean NOT NULL,
                    CONSTRAINT "PK_operacion_empernador_horometro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_empernador_horometro_operacion_empernador_v2_oper~" FOREIGN KEY (operacion_id) REFERENCES operacion_empernador_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_registro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    external_id bigint,
                    numero integer NOT NULL,
                    estado_principal text NOT NULL,
                    codigo_estado text NOT NULL,
                    estado_catalogo_id integer,
                    hora_inicio time without time zone NOT NULL,
                    hora_final time without time zone NOT NULL,
                    payload_operacion jsonb,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_empernador_registro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_empernador_registro_operacion_empernador_v2_opera~" FOREIGN KEY (operacion_id) REFERENCES operacion_empernador_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_checklist (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    checklist_item_id integer,
                    categoria_snapshot text NOT NULL,
                    descripcion_snapshot text NOT NULL,
                    decision integer NOT NULL,
                    observacion text,
                    CONSTRAINT "PK_operacion_scalamin_checklist" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scalamin_checklist_checklist_items_checklist_item~" FOREIGN KEY (checklist_item_id) REFERENCES checklist_items (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_operacion_scalamin_checklist_operacion_scalamin_v2_operacio~" FOREIGN KEY (operacion_id) REFERENCES operacion_scalamin_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_condicion_equipo (
                    operacion_id integer NOT NULL,
                    op boolean NOT NULL,
                    no_op boolean NOT NULL,
                    lugar text,
                    descripcion text,
                    aceite_motor boolean NOT NULL,
                    aceite_hidraulico boolean NOT NULL,
                    aceite_transmision boolean NOT NULL,
                    combustible text,
                    hora_llenado time without time zone,
                    CONSTRAINT "PK_operacion_scalamin_condicion_equipo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_scalamin_condicion_equipo_operacion_scalamin_v2_o~" FOREIGN KEY (operacion_id) REFERENCES operacion_scalamin_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_control_llanta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    posicion smallint NOT NULL,
                    estado boolean NOT NULL,
                    presion numeric(10,2),
                    observacion text,
                    CONSTRAINT "PK_operacion_scalamin_control_llanta" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scalamin_control_llanta_operacion_scalamin_v2_ope~" FOREIGN KEY (operacion_id) REFERENCES operacion_scalamin_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_horometro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    tipo text NOT NULL,
                    inicio numeric(10,2),
                    final numeric(10,2),
                    op boolean NOT NULL,
                    inop boolean NOT NULL,
                    CONSTRAINT "PK_operacion_scalamin_horometro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scalamin_horometro_operacion_scalamin_v2_operacio~" FOREIGN KEY (operacion_id) REFERENCES operacion_scalamin_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_registro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    external_id bigint,
                    numero integer NOT NULL,
                    estado_principal text NOT NULL,
                    codigo_estado text NOT NULL,
                    estado_catalogo_id integer,
                    hora_inicio time without time zone NOT NULL,
                    hora_final time without time zone NOT NULL,
                    payload_operacion jsonb,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_scalamin_registro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scalamin_registro_operacion_scalamin_v2_operacion~" FOREIGN KEY (operacion_id) REFERENCES operacion_scalamin_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_checklist (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    checklist_item_id integer,
                    categoria_snapshot text NOT NULL,
                    descripcion_snapshot text NOT NULL,
                    decision integer NOT NULL,
                    observacion text,
                    CONSTRAINT "PK_operacion_scissor_checklist" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scissor_checklist_checklist_items_checklist_item_~" FOREIGN KEY (checklist_item_id) REFERENCES checklist_items (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_operacion_scissor_checklist_operacion_scissor_v2_operacion_~" FOREIGN KEY (operacion_id) REFERENCES operacion_scissor_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_condicion_equipo (
                    operacion_id integer NOT NULL,
                    op boolean NOT NULL,
                    no_op boolean NOT NULL,
                    lugar text,
                    descripcion text,
                    aceite_motor boolean NOT NULL,
                    aceite_hidraulico boolean NOT NULL,
                    aceite_transmision boolean NOT NULL,
                    combustible text,
                    hora_llenado time without time zone,
                    CONSTRAINT "PK_operacion_scissor_condicion_equipo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_scissor_condicion_equipo_operacion_scissor_v2_ope~" FOREIGN KEY (operacion_id) REFERENCES operacion_scissor_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_control_llanta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    posicion smallint NOT NULL,
                    estado boolean NOT NULL,
                    presion numeric(10,2),
                    observacion text,
                    CONSTRAINT "PK_operacion_scissor_control_llanta" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scissor_control_llanta_operacion_scissor_v2_opera~" FOREIGN KEY (operacion_id) REFERENCES operacion_scissor_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_horometro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    tipo text NOT NULL,
                    inicio numeric(10,2),
                    final numeric(10,2),
                    op boolean NOT NULL,
                    inop boolean NOT NULL,
                    CONSTRAINT "PK_operacion_scissor_horometro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scissor_horometro_operacion_scissor_v2_operacion_~" FOREIGN KEY (operacion_id) REFERENCES operacion_scissor_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_registro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    external_id bigint,
                    numero integer NOT NULL,
                    estado_principal text NOT NULL,
                    codigo_estado text NOT NULL,
                    estado_catalogo_id integer,
                    hora_inicio time without time zone NOT NULL,
                    hora_final time without time zone NOT NULL,
                    payload_operacion jsonb,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_scissor_registro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_scissor_registro_operacion_scissor_v2_operacion_id" FOREIGN KEY (operacion_id) REFERENCES operacion_scissor_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_checklist (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    checklist_item_id integer,
                    categoria_snapshot text NOT NULL,
                    descripcion_snapshot text NOT NULL,
                    decision integer NOT NULL,
                    observacion text,
                    CONSTRAINT "PK_operacion_tal_horizontal_checklist" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_horizontal_checklist_checklist_items_checklis~" FOREIGN KEY (checklist_item_id) REFERENCES checklist_items (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_operacion_tal_horizontal_checklist_operacion_tal_horizontal~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_horizontal_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_condicion_equipo (
                    operacion_id integer NOT NULL,
                    op boolean NOT NULL,
                    no_op boolean NOT NULL,
                    lugar text,
                    descripcion text,
                    aceite_motor boolean NOT NULL,
                    aceite_hidraulico boolean NOT NULL,
                    aceite_transmision boolean NOT NULL,
                    combustible text,
                    hora_llenado time without time zone,
                    CONSTRAINT "PK_operacion_tal_horizontal_condicion_equipo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_tal_horizontal_condicion_equipo_operacion_tal_hor~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_horizontal_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_control_llanta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    posicion smallint NOT NULL,
                    estado boolean NOT NULL,
                    presion numeric(10,2),
                    observacion text,
                    CONSTRAINT "PK_operacion_tal_horizontal_control_llanta" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_horizontal_control_llanta_operacion_tal_horiz~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_horizontal_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_horometro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    tipo text NOT NULL,
                    inicio numeric(10,2),
                    final numeric(10,2),
                    op boolean NOT NULL,
                    inop boolean NOT NULL,
                    CONSTRAINT "PK_operacion_tal_horizontal_horometro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_horizontal_horometro_operacion_tal_horizontal~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_horizontal_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_registro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    external_id bigint,
                    numero integer NOT NULL,
                    estado_principal text NOT NULL,
                    codigo_estado text NOT NULL,
                    estado_catalogo_id integer,
                    hora_inicio time without time zone NOT NULL,
                    hora_final time without time zone NOT NULL,
                    payload_operacion jsonb,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_tal_horizontal_registro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_horizontal_registro_operacion_tal_horizontal_~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_horizontal_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_checklist (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    checklist_item_id integer,
                    categoria_snapshot text NOT NULL,
                    descripcion_snapshot text NOT NULL,
                    decision integer NOT NULL,
                    observacion text,
                    CONSTRAINT "PK_operacion_tal_largo_checklist" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_largo_checklist_checklist_items_checklist_ite~" FOREIGN KEY (checklist_item_id) REFERENCES checklist_items (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_operacion_tal_largo_checklist_operacion_tal_largo_v2_operac~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_largo_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_condicion_equipo (
                    operacion_id integer NOT NULL,
                    op boolean NOT NULL,
                    no_op boolean NOT NULL,
                    lugar text,
                    descripcion text,
                    aceite_motor boolean NOT NULL,
                    aceite_hidraulico boolean NOT NULL,
                    aceite_transmision boolean NOT NULL,
                    combustible text,
                    hora_llenado time without time zone,
                    CONSTRAINT "PK_operacion_tal_largo_condicion_equipo" PRIMARY KEY (operacion_id),
                    CONSTRAINT "FK_operacion_tal_largo_condicion_equipo_operacion_tal_largo_v2~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_largo_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_control_llanta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    posicion smallint NOT NULL,
                    estado boolean NOT NULL,
                    presion numeric(10,2),
                    observacion text,
                    CONSTRAINT "PK_operacion_tal_largo_control_llanta" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_largo_control_llanta_operacion_tal_largo_v2_o~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_largo_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_horometro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    tipo text NOT NULL,
                    inicio numeric(10,2),
                    final numeric(10,2),
                    op boolean NOT NULL,
                    inop boolean NOT NULL,
                    CONSTRAINT "PK_operacion_tal_largo_horometro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_largo_horometro_operacion_tal_largo_v2_operac~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_largo_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_registro (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    operacion_id integer NOT NULL,
                    external_id bigint,
                    numero integer NOT NULL,
                    estado_principal text NOT NULL,
                    codigo_estado text NOT NULL,
                    estado_catalogo_id integer,
                    hora_inicio time without time zone NOT NULL,
                    hora_final time without time zone NOT NULL,
                    payload_operacion jsonb,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_operacion_tal_largo_registro" PRIMARY KEY (id),
                    CONSTRAINT "FK_operacion_tal_largo_registro_operacion_tal_largo_v2_operaci~" FOREIGN KEY (operacion_id) REFERENCES operacion_tal_largo_v2 (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_carguio_registro_detalle (
                    registro_id integer NOT NULL,
                    nivel_inicio text,
                    tipo_labor_inicio text,
                    labor_inicio text,
                    ala_inicio text,
                    ubicacion_destino text,
                    n_cucharas integer,
                    observaciones text,
                    CONSTRAINT "PK_operacion_carguio_registro_detalle" PRIMARY KEY (registro_id),
                    CONSTRAINT "FK_operacion_carguio_registro_detalle_operacion_carguio_regist~" FOREIGN KEY (registro_id) REFERENCES operacion_carguio_registro (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_empernador_registro_detalle (
                    registro_id integer NOT NULL,
                    nivel text,
                    tipo_labor text,
                    labor text,
                    ala text,
                    tipo_pernos text,
                    log_pernos numeric(10,2),
                    n_pernos_instalados numeric(10,2),
                    tipo_malla text,
                    mt52_malla numeric(10,2),
                    sistematico_puntual text,
                    observaciones text,
                    CONSTRAINT "PK_operacion_empernador_registro_detalle" PRIMARY KEY (registro_id),
                    CONSTRAINT "FK_operacion_empernador_registro_detalle_operacion_empernador_~" FOREIGN KEY (registro_id) REFERENCES operacion_empernador_registro (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scalamin_registro_detalle (
                    registro_id integer NOT NULL,
                    nivel text,
                    tipo_labor text,
                    labor text,
                    ala text,
                    observaciones text,
                    CONSTRAINT "PK_operacion_scalamin_registro_detalle" PRIMARY KEY (registro_id),
                    CONSTRAINT "FK_operacion_scalamin_registro_detalle_operacion_scalamin_regi~" FOREIGN KEY (registro_id) REFERENCES operacion_scalamin_registro (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_scissor_registro_detalle (
                    registro_id integer NOT NULL,
                    origen_nivel text,
                    origen_tipo_labor text,
                    origen_labor text,
                    origen_ala text,
                    destino_nivel text,
                    destino_tipo_labor text,
                    destino_labor text,
                    destino_ala text,
                    observaciones text,
                    CONSTRAINT "PK_operacion_scissor_registro_detalle" PRIMARY KEY (registro_id),
                    CONSTRAINT "FK_operacion_scissor_registro_detalle_operacion_scissor_regist~" FOREIGN KEY (registro_id) REFERENCES operacion_scissor_registro (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_horizontal_registro_detalle (
                    registro_id integer NOT NULL,
                    nivel text,
                    tipo_labor text,
                    labor text,
                    ala text,
                    tal_prod numeric(10,2),
                    tal_rimados numeric(10,2),
                    tal_alivio numeric(10,2),
                    tal_repaso numeric(10,2),
                    long_barras numeric(10,2),
                    num_barras numeric(10,2),
                    tipo_perforacion text,
                    tipo_perforacion_id integer,
                    observaciones text,
                    CONSTRAINT "PK_operacion_tal_horizontal_registro_detalle" PRIMARY KEY (registro_id),
                    CONSTRAINT "FK_operacion_tal_horizontal_registro_detalle_operacion_tal_hor~" FOREIGN KEY (registro_id) REFERENCES operacion_tal_horizontal_registro (id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS operacion_tal_largo_registro_detalle (
                    registro_id integer NOT NULL,
                    nivel text,
                    tipo_labor text,
                    labor text,
                    ala text,
                    n_taladros_produccion text,
                    metros_perforados_produccion numeric(10,2),
                    n_taladros_rimados text,
                    metros_perforados_rimados numeric(10,2),
                    n_taladros_alivio text,
                    metros_perforados_alivio numeric(10,2),
                    n_taladros_repaso text,
                    metros_perforados_repaso numeric(10,2),
                    long_barras text,
                    num_barras text,
                    tipo_perforacion text,
                    tipo_perforacion_id integer,
                    observaciones text,
                    CONSTRAINT "PK_operacion_tal_largo_registro_detalle" PRIMARY KEY (registro_id),
                    CONSTRAINT "FK_operacion_tal_largo_registro_detalle_operacion_tal_largo_re~" FOREIGN KEY (registro_id) REFERENCES operacion_tal_largo_registro (id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_checklist_checklist_item_id" ON operacion_carguio_checklist (checklist_item_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_checklist_operacion_id" ON operacion_carguio_checklist (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_control_llanta_operacion_id" ON operacion_carguio_control_llanta (operacion_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_operacion_carguio_horometro_operacion_id_tipo" ON operacion_carguio_horometro (operacion_id, tipo);
                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_registro_codigo_estado" ON operacion_carguio_registro (codigo_estado);
                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_registro_estado_principal" ON operacion_carguio_registro (estado_principal);
                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_registro_operacion_id" ON operacion_carguio_registro (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_carguio_v2_seccion_id" ON operacion_carguio_v2 (seccion_id);

                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_checklist_checklist_item_id" ON operacion_empernador_checklist (checklist_item_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_checklist_operacion_id" ON operacion_empernador_checklist (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_control_llanta_operacion_id" ON operacion_empernador_control_llanta (operacion_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_operacion_empernador_horometro_operacion_id_tipo" ON operacion_empernador_horometro (operacion_id, tipo);
                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_registro_codigo_estado" ON operacion_empernador_registro (codigo_estado);
                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_registro_estado_principal" ON operacion_empernador_registro (estado_principal);
                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_registro_operacion_id" ON operacion_empernador_registro (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_empernador_v2_seccion_id" ON operacion_empernador_v2 (seccion_id);

                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_checklist_checklist_item_id" ON operacion_scalamin_checklist (checklist_item_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_checklist_operacion_id" ON operacion_scalamin_checklist (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_control_llanta_operacion_id" ON operacion_scalamin_control_llanta (operacion_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_operacion_scalamin_horometro_operacion_id_tipo" ON operacion_scalamin_horometro (operacion_id, tipo);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_registro_codigo_estado" ON operacion_scalamin_registro (codigo_estado);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_registro_estado_principal" ON operacion_scalamin_registro (estado_principal);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_registro_operacion_id" ON operacion_scalamin_registro (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scalamin_v2_seccion_id" ON operacion_scalamin_v2 (seccion_id);

                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_checklist_checklist_item_id" ON operacion_scissor_checklist (checklist_item_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_checklist_operacion_id" ON operacion_scissor_checklist (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_control_llanta_operacion_id" ON operacion_scissor_control_llanta (operacion_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_operacion_scissor_horometro_operacion_id_tipo" ON operacion_scissor_horometro (operacion_id, tipo);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_registro_codigo_estado" ON operacion_scissor_registro (codigo_estado);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_registro_estado_principal" ON operacion_scissor_registro (estado_principal);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_registro_operacion_id" ON operacion_scissor_registro (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_scissor_v2_seccion_id" ON operacion_scissor_v2 (seccion_id);

                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_checklist_checklist_item_id" ON operacion_tal_horizontal_checklist (checklist_item_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_checklist_operacion_id" ON operacion_tal_horizontal_checklist (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_control_llanta_operacion_id" ON operacion_tal_horizontal_control_llanta (operacion_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_horometro_operacion_id_tipo" ON operacion_tal_horizontal_horometro (operacion_id, tipo);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_registro_codigo_estado" ON operacion_tal_horizontal_registro (codigo_estado);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_registro_estado_principal" ON operacion_tal_horizontal_registro (estado_principal);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_registro_operacion_id" ON operacion_tal_horizontal_registro (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_horizontal_v2_seccion_id" ON operacion_tal_horizontal_v2 (seccion_id);

                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_checklist_checklist_item_id" ON operacion_tal_largo_checklist (checklist_item_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_checklist_operacion_id" ON operacion_tal_largo_checklist (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_control_llanta_operacion_id" ON operacion_tal_largo_control_llanta (operacion_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_operacion_tal_largo_horometro_operacion_id_tipo" ON operacion_tal_largo_horometro (operacion_id, tipo);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_registro_codigo_estado" ON operacion_tal_largo_registro (codigo_estado);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_registro_estado_principal" ON operacion_tal_largo_registro (estado_principal);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_registro_operacion_id" ON operacion_tal_largo_registro (operacion_id);
                CREATE INDEX IF NOT EXISTS "IX_operacion_tal_largo_v2_seccion_id" ON operacion_tal_largo_v2 (seccion_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
