// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Seminco.Infrastructure.Persistence;

#nullable disable

namespace Seminco.Infrastructure.Migrations
{
    [DbContext(typeof(SemincoDbContext))]
    [Migration("20260610201636_AddExploracionesYMediciones")]
    partial class AddExploracionesYMediciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("OperacionBaseSequence");

            modelBuilder.Entity("Seminco.Domain.Catalogs.Accesorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric")
                        .HasColumnName("costo");

                    b.Property<string>("TipoAccesorio")
                        .HasColumnType("text")
                        .HasColumnName("tipo_accesorio");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_accesorios_codigo");

                    b.ToTable("accesorios", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.CheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.HasKey("Id");

                    b.ToTable("checklist_items", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.ChecklistTelemando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("checklists_telemando", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnioFabricacion")
                        .HasColumnType("text")
                        .HasColumnName("anioFabricacion");

                    b.Property<double?>("CapacidadM3")
                        .HasColumnType("double precision")
                        .HasColumnName("capacidadM3");

                    b.Property<double?>("CapacidadYd3")
                        .HasColumnType("double precision")
                        .HasColumnName("capacidadYd3");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaIngreso");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<string>("Serie")
                        .HasColumnType("text")
                        .HasColumnName("serie");

                    b.HasKey("Id");

                    b.ToTable("equipos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("EstadoPrincipal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_principal");

                    b.Property<string>("Proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<string>("TipoEstado")
                        .HasColumnType("text")
                        .HasColumnName("tipo_estado");

                    b.HasKey("Id");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.Explosivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadPorCaja")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_por_caja");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<decimal?>("CostoPorKg")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_por_kg");

                    b.Property<double?>("PesoUnitario")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_unitario");

                    b.Property<string>("TipoExplosivo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_explosivo");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_explosivos_codigo");

                    b.ToTable("explosivos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.ExplosivoUni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Dato")
                        .HasColumnType("double precision")
                        .HasColumnName("dato");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("explisivos_uni", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.LongitudBarra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("LongitudPies")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud_pies");

                    b.Property<string>("Proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.HasKey("Id");

                    b.ToTable("longitud_barras", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.Malla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoMalla")
                        .HasColumnType("text")
                        .HasColumnName("tipo_malla");

                    b.HasKey("Id");

                    b.ToTable("mallas", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.NumeroRetardo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_numero_retardos_codigo");

                    b.ToTable("numero_retardos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.OrigenDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("origen_destino", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.Perno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("TipoPerno")
                        .HasColumnType("text")
                        .HasColumnName("tipo_perno");

                    b.HasKey("Id");

                    b.ToTable("pernos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.HasKey("Id");

                    b.ToTable("secciones", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.TipoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_equipos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Catalogs.TipoPerforacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int?>("PermitidoMedicion")
                        .HasColumnType("integer")
                        .HasColumnName("permitido_medicion");

                    b.Property<string>("Proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.HasKey("Id");

                    b.ToTable("tipoperforacions", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDespacho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DatosTrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("datos_trabajo_id");

                    b.Property<double>("MedioSegundo")
                        .HasColumnType("double precision")
                        .HasColumnName("medio_segundo");

                    b.Property<double>("MiliSegundo")
                        .HasColumnType("double precision")
                        .HasColumnName("mili_segundo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DatosTrabajoId");

                    b.ToTable("nube_despacho", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDespachoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DespachoId")
                        .HasColumnType("integer")
                        .HasColumnName("despacho_id");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_material");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DespachoId");

                    b.ToTable("nube_despacho_detalle", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDetalleDespachoExplosivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer")
                        .HasColumnName("id_despacho");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("Retardos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("retardos");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdDespacho");

                    b.ToTable("nube_detalle_despacho_explosivos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDetalleDevolucionExplosivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("IdDevolucion")
                        .HasColumnType("integer")
                        .HasColumnName("id_devolucion");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("Retardos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("retardos");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdDevolucion");

                    b.ToTable("nube_detalle_devoluciones_explosivos", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDevolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DatosTrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("datos_trabajo_id");

                    b.Property<double>("MedioSegundo")
                        .HasColumnType("double precision")
                        .HasColumnName("medio_segundo");

                    b.Property<double>("MiliSegundo")
                        .HasColumnType("double precision")
                        .HasColumnName("mili_segundo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DatosTrabajoId");

                    b.ToTable("nube_devoluciones", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDevolucionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DevolucionId")
                        .HasColumnType("integer")
                        .HasColumnName("devolucion_id");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_material");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DevolucionId");

                    b.ToTable("nube_devolucion_detalle", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeExploracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ala")
                        .HasColumnType("text")
                        .HasColumnName("ala");

                    b.Property<int>("Cerrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cerrado");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<int>("Envio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("envio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Creado")
                        .HasColumnName("estado");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fecha");

                    b.Property<string>("Labor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("labor");

                    b.Property<int>("Medicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("medicion");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("PiesPorTaladro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pies_por_taladro");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<string>("SemanaDefault")
                        .HasColumnType("text")
                        .HasColumnName("semanaDefault");

                    b.Property<string>("SemanaSelect")
                        .HasColumnType("text")
                        .HasColumnName("semanaSelect");

                    b.Property<string>("Taladro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taladro");

                    b.Property<string>("TipoLabor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_labor");

                    b.Property<string>("TipoPerforacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_perforacion");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Veta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("veta");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.ToTable("nube_datos_trabajo_exploraciones", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Mediciones.MedicionHorizontal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Alto")
                        .HasColumnType("double precision")
                        .HasColumnName("alto");

                    b.Property<double?>("Ancho")
                        .HasColumnType("double precision")
                        .HasColumnName("ancho");

                    b.Property<double?>("AvanceProgramado")
                        .HasColumnType("double precision")
                        .HasColumnName("avance_programado");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<int>("Envio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("envio");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdExplosivo")
                        .HasColumnType("integer")
                        .HasColumnName("id_explosivo");

                    b.Property<int?>("IdNube")
                        .HasColumnType("integer")
                        .HasColumnName("idnube");

                    b.Property<double?>("KgExplosivos")
                        .HasColumnType("double precision")
                        .HasColumnName("kg_explosivos");

                    b.Property<string>("Labor")
                        .HasColumnType("text")
                        .HasColumnName("labor");

                    b.Property<int>("NoAplica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("no_aplica");

                    b.Property<int>("Remanente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remanente");

                    b.Property<string>("TipoPerforacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_perforacion");

                    b.Property<string>("Turno")
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.Property<string>("Veta")
                        .HasColumnType("text")
                        .HasColumnName("veta");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.HasIndex("IdNube")
                        .IsUnique();

                    b.ToTable("mediciones_horizontal", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"OperacionBaseSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Aprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("aprobacion");

                    b.Property<string>("CheckList")
                        .HasColumnType("text")
                        .HasColumnName("check_list");

                    b.Property<string>("CondicionesEquipo")
                        .HasColumnType("text")
                        .HasColumnName("condiciones_equipo");

                    b.Property<string>("ControlLlantas")
                        .HasColumnType("text")
                        .HasColumnName("control_llantas");

                    b.Property<int>("Envio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("envio");

                    b.Property<string>("Equipo")
                        .HasColumnType("text")
                        .HasColumnName("equipo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<string>("Fecha")
                        .HasColumnType("text")
                        .HasColumnName("fecha");

                    b.Property<string>("Horometros")
                        .HasColumnType("text")
                        .HasColumnName("horometros");

                    b.Property<string>("JefeGuardia")
                        .HasColumnType("text")
                        .HasColumnName("jefe_guardia");

                    b.Property<string>("NEquipo")
                        .HasColumnType("text")
                        .HasColumnName("n_equipo");

                    b.Property<string>("ObservacionesJefe")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_jefe");

                    b.Property<string>("ObservacionesJefe2")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_jefe2");

                    b.Property<string>("ObservacionesJefe3")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_jefe3");

                    b.Property<string>("Operador")
                        .HasColumnType("text")
                        .HasColumnName("operador");

                    b.Property<string>("Registros")
                        .HasColumnType("text")
                        .HasColumnName("registros");

                    b.Property<int>("Revisado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("revisado");

                    b.Property<string>("Turno")
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Seminco.Domain.Planes.FechaPlanMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mes");

                    b.HasKey("Id");

                    b.ToTable("fechas_plan_mensual", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Planes.PlanMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ala")
                        .HasColumnType("text");

                    b.Property<double?>("AltoM")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnchoM")
                        .HasColumnType("double precision");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<double?>("AvanceM")
                        .HasColumnType("double precision");

                    b.Property<string>("Col10A")
                        .HasColumnType("text")
                        .HasColumnName("col_10A");

                    b.Property<string>("Col10B")
                        .HasColumnType("text")
                        .HasColumnName("col_10B");

                    b.Property<string>("Col11A")
                        .HasColumnType("text")
                        .HasColumnName("col_11A");

                    b.Property<string>("Col11B")
                        .HasColumnType("text")
                        .HasColumnName("col_11B");

                    b.Property<string>("Col12A")
                        .HasColumnType("text")
                        .HasColumnName("col_12A");

                    b.Property<string>("Col12B")
                        .HasColumnType("text")
                        .HasColumnName("col_12B");

                    b.Property<string>("Col13A")
                        .HasColumnType("text")
                        .HasColumnName("col_13A");

                    b.Property<string>("Col13B")
                        .HasColumnType("text")
                        .HasColumnName("col_13B");

                    b.Property<string>("Col14A")
                        .HasColumnType("text")
                        .HasColumnName("col_14A");

                    b.Property<string>("Col14B")
                        .HasColumnType("text")
                        .HasColumnName("col_14B");

                    b.Property<string>("Col15A")
                        .HasColumnType("text")
                        .HasColumnName("col_15A");

                    b.Property<string>("Col15B")
                        .HasColumnType("text")
                        .HasColumnName("col_15B");

                    b.Property<string>("Col16A")
                        .HasColumnType("text")
                        .HasColumnName("col_16A");

                    b.Property<string>("Col16B")
                        .HasColumnType("text")
                        .HasColumnName("col_16B");

                    b.Property<string>("Col17A")
                        .HasColumnType("text")
                        .HasColumnName("col_17A");

                    b.Property<string>("Col17B")
                        .HasColumnType("text")
                        .HasColumnName("col_17B");

                    b.Property<string>("Col18A")
                        .HasColumnType("text")
                        .HasColumnName("col_18A");

                    b.Property<string>("Col18B")
                        .HasColumnType("text")
                        .HasColumnName("col_18B");

                    b.Property<string>("Col19A")
                        .HasColumnType("text")
                        .HasColumnName("col_19A");

                    b.Property<string>("Col19B")
                        .HasColumnType("text")
                        .HasColumnName("col_19B");

                    b.Property<string>("Col1A")
                        .HasColumnType("text")
                        .HasColumnName("col_1A");

                    b.Property<string>("Col1B")
                        .HasColumnType("text")
                        .HasColumnName("col_1B");

                    b.Property<string>("Col20A")
                        .HasColumnType("text")
                        .HasColumnName("col_20A");

                    b.Property<string>("Col20B")
                        .HasColumnType("text")
                        .HasColumnName("col_20B");

                    b.Property<string>("Col21A")
                        .HasColumnType("text")
                        .HasColumnName("col_21A");

                    b.Property<string>("Col21B")
                        .HasColumnType("text")
                        .HasColumnName("col_21B");

                    b.Property<string>("Col22A")
                        .HasColumnType("text")
                        .HasColumnName("col_22A");

                    b.Property<string>("Col22B")
                        .HasColumnType("text")
                        .HasColumnName("col_22B");

                    b.Property<string>("Col23A")
                        .HasColumnType("text")
                        .HasColumnName("col_23A");

                    b.Property<string>("Col23B")
                        .HasColumnType("text")
                        .HasColumnName("col_23B");

                    b.Property<string>("Col24A")
                        .HasColumnType("text")
                        .HasColumnName("col_24A");

                    b.Property<string>("Col24B")
                        .HasColumnType("text")
                        .HasColumnName("col_24B");

                    b.Property<string>("Col25A")
                        .HasColumnType("text")
                        .HasColumnName("col_25A");

                    b.Property<string>("Col25B")
                        .HasColumnType("text")
                        .HasColumnName("col_25B");

                    b.Property<string>("Col26A")
                        .HasColumnType("text")
                        .HasColumnName("col_26A");

                    b.Property<string>("Col26B")
                        .HasColumnType("text")
                        .HasColumnName("col_26B");

                    b.Property<string>("Col27A")
                        .HasColumnType("text")
                        .HasColumnName("col_27A");

                    b.Property<string>("Col27B")
                        .HasColumnType("text")
                        .HasColumnName("col_27B");

                    b.Property<string>("Col28A")
                        .HasColumnType("text")
                        .HasColumnName("col_28A");

                    b.Property<string>("Col28B")
                        .HasColumnType("text")
                        .HasColumnName("col_28B");

                    b.Property<string>("Col2A")
                        .HasColumnType("text")
                        .HasColumnName("col_2A");

                    b.Property<string>("Col2B")
                        .HasColumnType("text")
                        .HasColumnName("col_2B");

                    b.Property<string>("Col3A")
                        .HasColumnType("text")
                        .HasColumnName("col_3A");

                    b.Property<string>("Col3B")
                        .HasColumnType("text")
                        .HasColumnName("col_3B");

                    b.Property<string>("Col4A")
                        .HasColumnType("text")
                        .HasColumnName("col_4A");

                    b.Property<string>("Col4B")
                        .HasColumnType("text")
                        .HasColumnName("col_4B");

                    b.Property<string>("Col5A")
                        .HasColumnType("text")
                        .HasColumnName("col_5A");

                    b.Property<string>("Col5B")
                        .HasColumnType("text")
                        .HasColumnName("col_5B");

                    b.Property<string>("Col6A")
                        .HasColumnType("text")
                        .HasColumnName("col_6A");

                    b.Property<string>("Col6B")
                        .HasColumnType("text")
                        .HasColumnName("col_6B");

                    b.Property<string>("Col7A")
                        .HasColumnType("text")
                        .HasColumnName("col_7A");

                    b.Property<string>("Col7B")
                        .HasColumnType("text")
                        .HasColumnName("col_7B");

                    b.Property<string>("Col8A")
                        .HasColumnType("text")
                        .HasColumnName("col_8A");

                    b.Property<string>("Col8B")
                        .HasColumnType("text")
                        .HasColumnName("col_8B");

                    b.Property<string>("Col9A")
                        .HasColumnType("text")
                        .HasColumnName("col_9A");

                    b.Property<string>("Col9B")
                        .HasColumnType("text")
                        .HasColumnName("col_9B");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Empresa")
                        .HasColumnType("text");

                    b.Property<string>("EstructuraVeta")
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .HasColumnType("text");

                    b.Property<string>("Labor")
                        .HasColumnType("text");

                    b.Property<string>("Mes")
                        .HasColumnType("text")
                        .HasColumnName("mes");

                    b.Property<string>("MinadoTipo")
                        .HasColumnType("text");

                    b.Property<string>("Nivel")
                        .HasColumnType("text");

                    b.Property<string>("Programado")
                        .HasColumnType("text")
                        .HasColumnName("programado");

                    b.Property<string>("TipoLabor")
                        .HasColumnType("text");

                    b.Property<string>("TipoMineral")
                        .HasColumnType("text");

                    b.Property<double?>("Tms")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Zona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("plan_mensual", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Planes.PlanMetraje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ala")
                        .HasColumnType("text");

                    b.Property<double?>("AnchoMinadoMes")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnchoMinadoSem")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnchoVeta")
                        .HasColumnType("double precision");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Block")
                        .HasColumnType("text");

                    b.Property<double?>("Burden")
                        .HasColumnType("double precision");

                    b.Property<string>("Col10A")
                        .HasColumnType("text")
                        .HasColumnName("columna_10A");

                    b.Property<string>("Col10B")
                        .HasColumnType("text")
                        .HasColumnName("columna_10B");

                    b.Property<string>("Col11A")
                        .HasColumnType("text")
                        .HasColumnName("columna_11A");

                    b.Property<string>("Col11B")
                        .HasColumnType("text")
                        .HasColumnName("columna_11B");

                    b.Property<string>("Col12A")
                        .HasColumnType("text")
                        .HasColumnName("columna_12A");

                    b.Property<string>("Col12B")
                        .HasColumnType("text")
                        .HasColumnName("columna_12B");

                    b.Property<string>("Col13A")
                        .HasColumnType("text")
                        .HasColumnName("columna_13A");

                    b.Property<string>("Col13B")
                        .HasColumnType("text")
                        .HasColumnName("columna_13B");

                    b.Property<string>("Col14A")
                        .HasColumnType("text")
                        .HasColumnName("columna_14A");

                    b.Property<string>("Col14B")
                        .HasColumnType("text")
                        .HasColumnName("columna_14B");

                    b.Property<string>("Col15A")
                        .HasColumnType("text")
                        .HasColumnName("columna_15A");

                    b.Property<string>("Col15B")
                        .HasColumnType("text")
                        .HasColumnName("columna_15B");

                    b.Property<string>("Col16A")
                        .HasColumnType("text")
                        .HasColumnName("columna_16A");

                    b.Property<string>("Col16B")
                        .HasColumnType("text")
                        .HasColumnName("columna_16B");

                    b.Property<string>("Col17A")
                        .HasColumnType("text")
                        .HasColumnName("columna_17A");

                    b.Property<string>("Col17B")
                        .HasColumnType("text")
                        .HasColumnName("columna_17B");

                    b.Property<string>("Col18A")
                        .HasColumnType("text")
                        .HasColumnName("columna_18A");

                    b.Property<string>("Col18B")
                        .HasColumnType("text")
                        .HasColumnName("columna_18B");

                    b.Property<string>("Col19A")
                        .HasColumnType("text")
                        .HasColumnName("columna_19A");

                    b.Property<string>("Col19B")
                        .HasColumnType("text")
                        .HasColumnName("columna_19B");

                    b.Property<string>("Col1A")
                        .HasColumnType("text")
                        .HasColumnName("columna_1A");

                    b.Property<string>("Col1B")
                        .HasColumnType("text")
                        .HasColumnName("columna_1B");

                    b.Property<string>("Col20A")
                        .HasColumnType("text")
                        .HasColumnName("columna_20A");

                    b.Property<string>("Col20B")
                        .HasColumnType("text")
                        .HasColumnName("columna_20B");

                    b.Property<string>("Col21A")
                        .HasColumnType("text")
                        .HasColumnName("columna_21A");

                    b.Property<string>("Col21B")
                        .HasColumnType("text")
                        .HasColumnName("columna_21B");

                    b.Property<string>("Col22A")
                        .HasColumnType("text")
                        .HasColumnName("columna_22A");

                    b.Property<string>("Col22B")
                        .HasColumnType("text")
                        .HasColumnName("columna_22B");

                    b.Property<string>("Col23A")
                        .HasColumnType("text")
                        .HasColumnName("columna_23A");

                    b.Property<string>("Col23B")
                        .HasColumnType("text")
                        .HasColumnName("columna_23B");

                    b.Property<string>("Col24A")
                        .HasColumnType("text")
                        .HasColumnName("columna_24A");

                    b.Property<string>("Col24B")
                        .HasColumnType("text")
                        .HasColumnName("columna_24B");

                    b.Property<string>("Col25A")
                        .HasColumnType("text")
                        .HasColumnName("columna_25A");

                    b.Property<string>("Col25B")
                        .HasColumnType("text")
                        .HasColumnName("columna_25B");

                    b.Property<string>("Col26A")
                        .HasColumnType("text")
                        .HasColumnName("columna_26A");

                    b.Property<string>("Col26B")
                        .HasColumnType("text")
                        .HasColumnName("columna_26B");

                    b.Property<string>("Col27A")
                        .HasColumnType("text")
                        .HasColumnName("columna_27A");

                    b.Property<string>("Col27B")
                        .HasColumnType("text")
                        .HasColumnName("columna_27B");

                    b.Property<string>("Col28A")
                        .HasColumnType("text")
                        .HasColumnName("columna_28A");

                    b.Property<string>("Col28B")
                        .HasColumnType("text")
                        .HasColumnName("columna_28B");

                    b.Property<string>("Col2A")
                        .HasColumnType("text")
                        .HasColumnName("columna_2A");

                    b.Property<string>("Col2B")
                        .HasColumnType("text")
                        .HasColumnName("columna_2B");

                    b.Property<string>("Col3A")
                        .HasColumnType("text")
                        .HasColumnName("columna_3A");

                    b.Property<string>("Col3B")
                        .HasColumnType("text")
                        .HasColumnName("columna_3B");

                    b.Property<string>("Col4A")
                        .HasColumnType("text")
                        .HasColumnName("columna_4A");

                    b.Property<string>("Col4B")
                        .HasColumnType("text")
                        .HasColumnName("columna_4B");

                    b.Property<string>("Col5A")
                        .HasColumnType("text")
                        .HasColumnName("columna_5A");

                    b.Property<string>("Col5B")
                        .HasColumnType("text")
                        .HasColumnName("columna_5B");

                    b.Property<string>("Col6A")
                        .HasColumnType("text")
                        .HasColumnName("columna_6A");

                    b.Property<string>("Col6B")
                        .HasColumnType("text")
                        .HasColumnName("columna_6B");

                    b.Property<string>("Col7A")
                        .HasColumnType("text")
                        .HasColumnName("columna_7A");

                    b.Property<string>("Col7B")
                        .HasColumnType("text")
                        .HasColumnName("columna_7B");

                    b.Property<string>("Col8A")
                        .HasColumnType("text")
                        .HasColumnName("columna_8A");

                    b.Property<string>("Col8B")
                        .HasColumnType("text")
                        .HasColumnName("columna_8B");

                    b.Property<string>("Col9A")
                        .HasColumnType("text")
                        .HasColumnName("columna_9A");

                    b.Property<string>("Col9B")
                        .HasColumnType("text")
                        .HasColumnName("columna_9B");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<double?>("Espaciamiento")
                        .HasColumnType("double precision");

                    b.Property<string>("EstructuraVeta")
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .HasColumnType("text");

                    b.Property<string>("Labor")
                        .HasColumnType("text");

                    b.Property<double?>("LongitudPerforacion")
                        .HasColumnType("double precision");

                    b.Property<string>("Mes")
                        .HasColumnType("text")
                        .HasColumnName("mes");

                    b.Property<string>("Mina")
                        .HasColumnType("text");

                    b.Property<string>("MinadoTipo")
                        .HasColumnType("text");

                    b.Property<string>("Nivel")
                        .HasColumnType("text");

                    b.Property<string>("Programado")
                        .HasColumnType("text")
                        .HasColumnName("programado");

                    b.Property<string>("Semana")
                        .HasColumnType("text");

                    b.Property<string>("TipoLabor")
                        .HasColumnType("text");

                    b.Property<string>("TipoMineral")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Zona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("planmetraje", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Planes.PlanProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AgGr")
                        .HasColumnType("double precision");

                    b.Property<string>("Ala")
                        .HasColumnType("text");

                    b.Property<double?>("AnchoMinadoMes")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnchoMinadoSem")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnchoVeta")
                        .HasColumnType("double precision");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Block")
                        .HasColumnType("text");

                    b.Property<string>("Col10A")
                        .HasColumnType("text")
                        .HasColumnName("columna_10A");

                    b.Property<string>("Col10B")
                        .HasColumnType("text")
                        .HasColumnName("columna_10B");

                    b.Property<string>("Col11A")
                        .HasColumnType("text")
                        .HasColumnName("columna_11A");

                    b.Property<string>("Col11B")
                        .HasColumnType("text")
                        .HasColumnName("columna_11B");

                    b.Property<string>("Col12A")
                        .HasColumnType("text")
                        .HasColumnName("columna_12A");

                    b.Property<string>("Col12B")
                        .HasColumnType("text")
                        .HasColumnName("columna_12B");

                    b.Property<string>("Col13A")
                        .HasColumnType("text")
                        .HasColumnName("columna_13A");

                    b.Property<string>("Col13B")
                        .HasColumnType("text")
                        .HasColumnName("columna_13B");

                    b.Property<string>("Col14A")
                        .HasColumnType("text")
                        .HasColumnName("columna_14A");

                    b.Property<string>("Col14B")
                        .HasColumnType("text")
                        .HasColumnName("columna_14B");

                    b.Property<string>("Col15A")
                        .HasColumnType("text")
                        .HasColumnName("columna_15A");

                    b.Property<string>("Col15B")
                        .HasColumnType("text")
                        .HasColumnName("columna_15B");

                    b.Property<string>("Col16A")
                        .HasColumnType("text")
                        .HasColumnName("columna_16A");

                    b.Property<string>("Col16B")
                        .HasColumnType("text")
                        .HasColumnName("columna_16B");

                    b.Property<string>("Col17A")
                        .HasColumnType("text")
                        .HasColumnName("columna_17A");

                    b.Property<string>("Col17B")
                        .HasColumnType("text")
                        .HasColumnName("columna_17B");

                    b.Property<string>("Col18A")
                        .HasColumnType("text")
                        .HasColumnName("columna_18A");

                    b.Property<string>("Col18B")
                        .HasColumnType("text")
                        .HasColumnName("columna_18B");

                    b.Property<string>("Col19A")
                        .HasColumnType("text")
                        .HasColumnName("columna_19A");

                    b.Property<string>("Col19B")
                        .HasColumnType("text")
                        .HasColumnName("columna_19B");

                    b.Property<string>("Col1A")
                        .HasColumnType("text")
                        .HasColumnName("columna_1A");

                    b.Property<string>("Col1B")
                        .HasColumnType("text")
                        .HasColumnName("columna_1B");

                    b.Property<string>("Col20A")
                        .HasColumnType("text")
                        .HasColumnName("columna_20A");

                    b.Property<string>("Col20B")
                        .HasColumnType("text")
                        .HasColumnName("columna_20B");

                    b.Property<string>("Col21A")
                        .HasColumnType("text")
                        .HasColumnName("columna_21A");

                    b.Property<string>("Col21B")
                        .HasColumnType("text")
                        .HasColumnName("columna_21B");

                    b.Property<string>("Col22A")
                        .HasColumnType("text")
                        .HasColumnName("columna_22A");

                    b.Property<string>("Col22B")
                        .HasColumnType("text")
                        .HasColumnName("columna_22B");

                    b.Property<string>("Col23A")
                        .HasColumnType("text")
                        .HasColumnName("columna_23A");

                    b.Property<string>("Col23B")
                        .HasColumnType("text")
                        .HasColumnName("columna_23B");

                    b.Property<string>("Col24A")
                        .HasColumnType("text")
                        .HasColumnName("columna_24A");

                    b.Property<string>("Col24B")
                        .HasColumnType("text")
                        .HasColumnName("columna_24B");

                    b.Property<string>("Col25A")
                        .HasColumnType("text")
                        .HasColumnName("columna_25A");

                    b.Property<string>("Col25B")
                        .HasColumnType("text")
                        .HasColumnName("columna_25B");

                    b.Property<string>("Col26A")
                        .HasColumnType("text")
                        .HasColumnName("columna_26A");

                    b.Property<string>("Col26B")
                        .HasColumnType("text")
                        .HasColumnName("columna_26B");

                    b.Property<string>("Col27A")
                        .HasColumnType("text")
                        .HasColumnName("columna_27A");

                    b.Property<string>("Col27B")
                        .HasColumnType("text")
                        .HasColumnName("columna_27B");

                    b.Property<string>("Col28A")
                        .HasColumnType("text")
                        .HasColumnName("columna_28A");

                    b.Property<string>("Col28B")
                        .HasColumnType("text")
                        .HasColumnName("columna_28B");

                    b.Property<string>("Col2A")
                        .HasColumnType("text")
                        .HasColumnName("columna_2A");

                    b.Property<string>("Col2B")
                        .HasColumnType("text")
                        .HasColumnName("columna_2B");

                    b.Property<string>("Col3A")
                        .HasColumnType("text")
                        .HasColumnName("columna_3A");

                    b.Property<string>("Col3B")
                        .HasColumnType("text")
                        .HasColumnName("columna_3B");

                    b.Property<string>("Col4A")
                        .HasColumnType("text")
                        .HasColumnName("columna_4A");

                    b.Property<string>("Col4B")
                        .HasColumnType("text")
                        .HasColumnName("columna_4B");

                    b.Property<string>("Col5A")
                        .HasColumnType("text")
                        .HasColumnName("columna_5A");

                    b.Property<string>("Col5B")
                        .HasColumnType("text")
                        .HasColumnName("columna_5B");

                    b.Property<string>("Col6A")
                        .HasColumnType("text")
                        .HasColumnName("columna_6A");

                    b.Property<string>("Col6B")
                        .HasColumnType("text")
                        .HasColumnName("columna_6B");

                    b.Property<string>("Col7A")
                        .HasColumnType("text")
                        .HasColumnName("columna_7A");

                    b.Property<string>("Col7B")
                        .HasColumnType("text")
                        .HasColumnName("columna_7B");

                    b.Property<string>("Col8A")
                        .HasColumnType("text")
                        .HasColumnName("columna_8A");

                    b.Property<string>("Col8B")
                        .HasColumnType("text")
                        .HasColumnName("columna_8B");

                    b.Property<string>("Col9A")
                        .HasColumnType("text")
                        .HasColumnName("columna_9A");

                    b.Property<string>("Col9B")
                        .HasColumnType("text")
                        .HasColumnName("columna_9B");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<double?>("CutOff1")
                        .HasColumnType("double precision");

                    b.Property<double?>("CutOff2")
                        .HasColumnType("double precision");

                    b.Property<string>("EstructuraVeta")
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .HasColumnType("text");

                    b.Property<string>("Labor")
                        .HasColumnType("text");

                    b.Property<string>("Mes")
                        .HasColumnType("text")
                        .HasColumnName("mes");

                    b.Property<string>("Mina")
                        .HasColumnType("text");

                    b.Property<string>("MinadoTipo")
                        .HasColumnType("text");

                    b.Property<string>("Nivel")
                        .HasColumnType("text");

                    b.Property<double?>("PorcentajeCu")
                        .HasColumnType("double precision");

                    b.Property<double?>("PorcentajePb")
                        .HasColumnType("double precision");

                    b.Property<double?>("PorcentajeZn")
                        .HasColumnType("double precision");

                    b.Property<string>("Programado")
                        .HasColumnType("text")
                        .HasColumnName("programado");

                    b.Property<string>("Semana")
                        .HasColumnType("text");

                    b.Property<string>("TipoLabor")
                        .HasColumnType("text");

                    b.Property<string>("TipoMineral")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<double?>("VptAct")
                        .HasColumnType("double precision");

                    b.Property<double?>("VptFinal")
                        .HasColumnType("double precision");

                    b.Property<string>("Zona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("planproduccions", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("AutorizadoEquipo")
                        .HasColumnType("text")
                        .HasColumnName("autorizado_equipo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Clasificacion")
                        .HasColumnType("text")
                        .HasColumnName("clasificacion");

                    b.Property<string>("CodigoDni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_dni");

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Firma")
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Guardia")
                        .HasColumnType("text")
                        .HasColumnName("guardia");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<string>("OperacionesAutorizadas")
                        .HasColumnType("jsonb")
                        .HasColumnName("operaciones_autorizadas");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CodigoDni")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_codigo_dni");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo")
                        .HasFilter("\"correo\" IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionAnfochanger", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("ModeloEquipo")
                        .HasColumnType("text")
                        .HasColumnName("modelo_equipo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.ToTable("Operacion_anfochanger", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionCarguio", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("Capacidad")
                        .HasColumnType("text")
                        .HasColumnName("capacidad");

                    b.Property<string>("ProgramaTrabajo")
                        .HasColumnType("text")
                        .HasColumnName("programa_trabajo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<string>("TipoEquipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_equipo");

                    b.ToTable("Operacion_carguio", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionDumper", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("Capacidad")
                        .HasColumnType("text")
                        .HasColumnName("capacidad");

                    b.Property<string>("CheckListTelemando")
                        .HasColumnType("text")
                        .HasColumnName("check_list_telemando");

                    b.Property<string>("ProgramaTrabajo")
                        .HasColumnType("text")
                        .HasColumnName("programa_trabajo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<string>("TipoEquipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_equipo");

                    b.ToTable("Operacion_dumper", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionEmpernador", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<string>("TipoEquipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_equipo");

                    b.ToTable("Operacion_empernador", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionRompebanco", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.ToTable("Operacion_rompebanco", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionScalamin", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("ModeloEquipo")
                        .HasColumnType("text")
                        .HasColumnName("modelo_equipo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.ToTable("Operacion_scalamin", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionScissor", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("ModeloEquipo")
                        .HasColumnType("text")
                        .HasColumnName("modelo_equipo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.ToTable("Operacion_scissor", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionTalHorizontal", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("ModeloEquipo")
                        .HasColumnType("text")
                        .HasColumnName("modelo_equipo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.ToTable("Operacion_tal_horizontal", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Operaciones.OperacionTalLargo", b =>
                {
                    b.HasBaseType("Seminco.Domain.Operaciones.OperacionBase");

                    b.Property<string>("ModeloEquipo")
                        .HasColumnType("text")
                        .HasColumnName("modelo_equipo");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.ToTable("Operacion_tal_largo", (string)null);
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDespacho", b =>
                {
                    b.HasOne("Seminco.Domain.Exploraciones.NubeExploracion", "DatosTrabajo")
                        .WithMany("Despachos")
                        .HasForeignKey("DatosTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosTrabajo");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDespachoDetalle", b =>
                {
                    b.HasOne("Seminco.Domain.Exploraciones.NubeDespacho", "Despacho")
                        .WithMany("Detalles")
                        .HasForeignKey("DespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despacho");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDetalleDespachoExplosivo", b =>
                {
                    b.HasOne("Seminco.Domain.Exploraciones.NubeDespacho", "Despacho")
                        .WithMany("DetallesExplosivos")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despacho");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDetalleDevolucionExplosivo", b =>
                {
                    b.HasOne("Seminco.Domain.Exploraciones.NubeDevolucion", "Devolucion")
                        .WithMany("DetallesExplosivos")
                        .HasForeignKey("IdDevolucion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devolucion");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDevolucion", b =>
                {
                    b.HasOne("Seminco.Domain.Exploraciones.NubeExploracion", "DatosTrabajo")
                        .WithMany("Devoluciones")
                        .HasForeignKey("DatosTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosTrabajo");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDevolucionDetalle", b =>
                {
                    b.HasOne("Seminco.Domain.Exploraciones.NubeDevolucion", "Devolucion")
                        .WithMany("Detalles")
                        .HasForeignKey("DevolucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devolucion");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDespacho", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("DetallesExplosivos");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeDevolucion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("DetallesExplosivos");
                });

            modelBuilder.Entity("Seminco.Domain.Exploraciones.NubeExploracion", b =>
                {
                    b.Navigation("Despachos");

                    b.Navigation("Devoluciones");
                });
#pragma warning restore 612, 618
        }
    }
}
