// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Seminco.Infrastructure.Persistence;

#nullable disable

namespace Seminco.Infrastructure.Migrations
{
    [DbContext(typeof(SemincoDbContext))]
    partial class SemincoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Seminco.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("AutorizadoEquipo")
                        .HasColumnType("text")
                        .HasColumnName("autorizado_equipo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Clasificacion")
                        .HasColumnType("text")
                        .HasColumnName("clasificacion");

                    b.Property<string>("CodigoDni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_dni");

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Firma")
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Guardia")
                        .HasColumnType("text")
                        .HasColumnName("guardia");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<string>("OperacionesAutorizadas")
                        .HasColumnType("jsonb")
                        .HasColumnName("operaciones_autorizadas");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CodigoDni")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_codigo_dni");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo")
                        .HasFilter("\"correo\" IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
